let ctx=null,master=null;
function ensure(){if(ctx)return ctx;const AC=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AC)return null;ctx=new AC();master=ctx.createGain();master.gain.value=.16;master.connect(ctx.destination);return ctx;}
export function unlockVerityAudio(){const c=ensure();if(c?.state==='suspended')c.resume();}
export function setVerityVolume(v){ensure();if(master)master.gain.value=Math.max(0,Math.min(.5,Number(v)||0));}
export function chime(){tone(660,.12,.12,'sine');setTimeout(()=>tone(990,.17,.08,'triangle'),90);}
export function boxOpen(){noise(.18,.18,900);setTimeout(()=>tone(420,.22,.1,'triangle'),80);}
export function whisper(intensity=.6){const c=ensure();if(!c)return;const dur=.7+intensity*.8,buffer=c.createBuffer(1,Math.floor(c.sampleRate*dur),c.sampleRate),d=buffer.getChannelData(0);for(let i=0;i<d.length;i++){const t=i/d.length;d[i]=(Math.random()*2-1)*Math.pow(1-t,1.7)*(.15+Math.sin(i*.003)*.04);}const src=c.createBufferSource();src.buffer=buffer;const filter=c.createBiquadFilter();filter.type='bandpass';filter.frequency.value=500+intensity*800;filter.Q.value=1.7;const g=c.createGain();g.gain.value=.22*intensity;src.connect(filter);filter.connect(g);g.connect(master);src.start();}
export function shriek(){tone(90,.7,.24,'sawtooth',860);noise(.55,.3,1500);}
export function demonBreath(){noise(1.4,.2,180);tone(52,1.2,.07,'sawtooth',42);}
export function wrongStep(){noise(.08,.08,250);setTimeout(()=>noise(.09,.05,190),120);}
export function blackout(){tone(42,.45,.16,'sine',24);noise(.22,.1,70);}
export function endingTone(kind){if(kind==='reconcile'){tone(440,.7,.1,'sine',660);setTimeout(()=>tone(880,.8,.08,'sine'),400);}else if(kind==='rupture'){tone(180,.55,.16,'square',60);setTimeout(()=>noise(.5,.15,1200),180);}else{tone(60,1.5,.18,'sawtooth',30);}}
function tone(freq,dur,vol=.1,type='sine',endFreq=null){const c=ensure();if(!c||!master)return;const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,c.currentTime);if(endFreq)o.frequency.exponentialRampToValueAtTime(Math.max(1,endFreq),c.currentTime+dur);g.gain.setValueAtTime(0,c.currentTime);g.gain.linearRampToValueAtTime(vol,c.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+dur);o.connect(g);g.connect(master);o.start();o.stop(c.currentTime+dur+.03);}
function noise(dur,vol=.1,cutoff=800){const c=ensure();if(!c||!master)return;const b=c.createBuffer(1,Math.floor(c.sampleRate*dur),c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;const s=c.createBufferSource();s.buffer=b;const f=c.createBiquadFilter();f.type='lowpass';f.frequency.value=cutoff;const g=c.createGain();g.gain.setValueAtTime(vol,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+dur);s.connect(f);f.connect(g);g.connect(master);s.start();}
