import { findPath2D } from '../../v1/entities.js';
import { VERITY_PHASES } from './state.js';

export class VerityBehavior{
  constructor(world,state){this.world=world;this.state=state;this.abandonClock=0;this.demonPath=[];this.demonPathClock=0;this.friendPath=[];this.friendPathClock=0;}
  setWorld(world,state=this.state){this.world=world;this.state=state;this.demonPath=[];this.friendPath=[];this.demonPathClock=this.friendPathClock=0;}
  tickCompanion(dt,player){const s=this.state,v=s.verity;if(!v.active||!v.visible||s.phase>=VERITY_PHASES.DEMON)return{distance:Infinity,moved:false};const distance=Math.hypot(player.x-v.x,player.z-v.z);if(distance>35){this.abandonClock+=dt;if(this.abandonClock>=30){this.abandonClock=0;s.apply('abandon',1,{text:'O jogador ficou longe de Verity por bastante tempo.'});}}else this.abandonClock=Math.max(0,this.abandonClock-dt*2);if(!v.follow)return{distance,moved:false};if(distance>46){v.x=player.x-3;v.z=player.z-3;v.y=player.y+.45;s.memory.remember('movement','Verity alcançou o jogador depois de ficar muito longe.',1);this.friendPath=[];return{distance,moved:true,teleported:true};}if(distance<=2.7){v.y+=(player.y+.45-v.y)*Math.min(1,dt*3);return{distance,moved:false};}
    this.friendPathClock-=dt;if(this.friendPathClock<=0){this.friendPathClock=.8;this.friendPath=findPath2D(this.world,{x:v.x,z:v.z},{x:player.x,z:player.z},14,120)||[];}
    const target=this.friendPath[0]||player;if(this.friendPath.length&&Math.hypot(target.x-v.x,target.z-v.z)<.45)this.friendPath.shift();const dx=target.x-v.x,dz=target.z-v.z,len=Math.hypot(dx,dz)||1,speed=1.65+Math.min(1.25,s.dependency*.011),nx=v.x+dx/len*speed*dt,nz=v.z+dz/len*speed*dt,ny=this.world.surfaceY(nx,nz);if(Math.abs(ny-v.y)<=1.6&&this.world.isWalkable(nx,ny,nz)){v.x=nx;v.z=nz;v.y+=(ny+.35-v.y)*Math.min(1,dt*5);return{distance,moved:true};}this.friendPathClock=0;return{distance,moved:false,blocked:true};}
  tickDemon(dt,player,{frozen=false}={}){const d=this.state.demon;if(!d.active||frozen)return{distance:Math.hypot(player.x-d.x,player.z-d.z),moved:false};const distance=Math.hypot(player.x-d.x,player.z-d.z);this.demonPathClock-=dt;if(this.demonPathClock<=0){this.demonPathClock=.55+Math.random()*.3;this.demonPath=findPath2D(this.world,{x:d.x,z:d.z},{x:player.x,z:player.z},20,180)||[];}
    let target=this.demonPath[0]||player;if(this.demonPath.length&&Math.hypot(target.x-d.x,target.z-d.z)<.5){this.demonPath.shift();target=this.demonPath[0]||player;}const dx=target.x-d.x,dz=target.z-d.z,len=Math.hypot(dx,dz)||1,speed=2.1+this.state.resentment*.014+Math.min(1.3,this.state.corruption*.013),nx=d.x+dx/len*speed*dt,nz=d.z+dz/len*speed*dt,ny=this.world.surfaceY(nx,nz);if(Math.abs(ny-d.y)<=2.2&&this.world.isWalkable(nx,ny,nz)){d.x=nx;d.z=nz;d.y+=(ny-d.y)*Math.min(1,dt*3.4);return{distance,moved:true,pathing:this.demonPath.length>0};}this.demonPathClock=0;return{distance,moved:false,blocked:true};}
  knockCompanion(player,strength=2.8){const v=this.state.verity,dx=v.x-player.x,dz=v.z-player.z,len=Math.hypot(dx,dz)||1;v.x+=dx/len*strength;v.z+=dz/len*strength;v.y=this.world.surfaceY(v.x,v.z)+.35;this.friendPath=[];}
}
