import { SaveDB } from '../../v1/save-db.js';
import { itemDef } from '../../v1/catalog.js';
import { VerityState, VERITY_PHASES } from './state.js';
import { VerityBrain, RemoteVerityProvider } from './brain.js';
import { HorrorDirector } from './director.js';
import { VerityBehavior } from './behavior.js';
import { loadVerityConfig, saveVerityConfig, applyPreset } from './config.js';
import { unlockedLore, loreProgress, markLoreRead } from './lore.js';
import { initializeVerityLandmarks, maybeGenerateLandmarks, distanceToShrine } from './structures.js';
import { VerityRenderer } from './renderer.js';
import { VerityUI } from './ui.js';
import { VITEM, registerVerityContent } from './content.js';
import { unlockVerityAudio, chime, boxOpen, whisper, shriek, demonBreath, wrongStep, blackout, endingTone, playFrequency17 } from './audio.js';

registerVerityContent();
const api=await waitForApi();
if(api)boot(api);

async function boot(api){
  const db=new SaveDB();await db.open();let worldId=api.state().worldId,state=null,brain=null,director=null,behavior=null,config=loadVerityConfig(),last=performance.now(),saveClock=0,lastHealth=api.stats.health,previousPhase=-1,worldOff=null,lanternCooldown=0,networkStamp=0;
  const renderer=new VerityRenderer();
  const ui=new VerityUI({onSend:ask,onInteract:interact,onLantern:useLantern,onArchive:toggleArchive,onSettings:configureSettings});ui.setConfig(config);
  await loadWorldState(worldId);bindWorld();
  document.body.addEventListener('pointerdown',unlockVerityAudio,{once:true});
  addEventListener('keydown',onKey);const gameCanvas=document.querySelector('#game');gameCanvas?.addEventListener('mousedown',onUse,{capture:true});gameCanvas?.addEventListener('mousedown',onAttack);
  addEventListener('voxelcraft:mod-network',onNetwork);
  const loop=setInterval(tick,50);addEventListener('beforeunload',()=>{persist();clearInterval(loop);renderer.dispose();worldOff?.();});
  window.VerityMod={get state(){return state},get brain(){return brain},get config(){return{...config}},forcePhase:(p)=>{state.forcePhase(p);phaseChanged(true);return state.phase;},event:(id)=>director?.fire?.({id,min:state.phase,weight:1},{...context(),api}),save:persist,interact,ask,useLantern,archive:()=>loreProgress(state,api.inventory),generate:()=>maybeGenerateLandmarks(api.world,state,position(),{radius:99999}),setConfig:(next)=>configureSettings({...config,...next,preset:next?.preset||'custom'})};

  async function loadWorldState(id){const raw=await db.get('addons',`${id}:verity`);state=new VerityState(api.world.seed);if(raw)state.load(raw);state.lastWorldId=id;const p=position();if(!state.box.spawned)spawnBox(p);initializeVerityLandmarks(api.world,state,p);brain=new VerityBrain(state);behavior=behavior?Object.assign(behavior,{state}):new VerityBehavior(api.world,state);behavior.setWorld(api.world,state);const mode=localStorage.getItem('verity-ai-mode')||'offline',endpoint=localStorage.getItem('verity-ai-endpoint')||'';ui.setAIConfig({mode,endpoint});if(mode==='remote'&&endpoint){brain.setRemote(new RemoteVerityProvider({endpoint}));brain.setMode('remote');}director=new HorrorDirector(state,{onEvent:handleHorrorEvent,config});previousPhase=state.phase;ui.restoreMessages(state.memory.entries);syncMood();}
  function bindWorld(){worldOff?.();worldOff=api.world.onChange?.((e)=>{if(e.type!=='block'||!state.verity.active)return;const d=Math.hypot((e.x+.5)-state.verity.x,(e.y+.5)-state.verity.y,(e.z+.5)-state.verity.z);if(d<8){state.metrics.blocksChangedNearVerity++;if(e.id===0&&d<2.2&&Math.random()<.08)state.apply('hit',.2,{text:'Bloco quebrado muito perto de Verity'});}});}
  async function switchWorld(next){await persist();worldId=next;await loadWorldState(next);bindWorld();}
  function spawnBox(p){const r=seeded(state.seed),a=r()*Math.PI*2,dist=7+r()*7;state.box={spawned:true,opened:false,x:p.x+Math.cos(a)*dist,y:p.y+.1,z:p.z+Math.sin(a)*dist};const sy=api.world.surfaceY(state.box.x,state.box.z);if(Number.isFinite(sy)&&Math.abs(sy-p.y)<10)state.box.y=sy+.08;state.memory.remember('system','A caixa apareceu no mundo.',2,{x:state.box.x,y:state.box.y,z:state.box.z});}
  function tick(){const now=performance.now(),dt=Math.min(.25,Math.max(0,(now-last)/1000));last=now;const current=api.state();if(current.worldId!==worldId){switchWorld(current.worldId);return;}const p=position(),boxDist=dist3(p,state.box),verityDist=dist3(p,state.verity);state.tick(dt,{distance:verityDist,near:verityDist<12,intensity:config.intensity});
    if(state.box.opened&&!state.ending){updateVerity(dt,p);if(state.phase>=VERITY_PHASES.DEMON)updateDemon(dt,p);director.tick(dt,{...context(),api});maybeGenerateLandmarks(api.world,state,p);if(!state.eastVillage.visited&&state.eastVillage.generated&&Math.hypot(p.x-state.eastVillage.x,p.z-state.eastVillage.z)<26){state.eastVillage.visited=true;state.apply('investigate',5,{text:'Chegou à aldeia a leste.'});ui.add('verity','Você veio mesmo. Eu pedi para não vir.');}}
    if(state.phase!==previousPhase)phaseChanged();renderer.update(state,p,dt);updatePrompt(boxDist,verityDist,p);syncMood();saveClock+=dt;lanternCooldown=Math.max(0,lanternCooldown-dt);if(saveClock>8){saveClock=0;persist();}
    if(lastHealth>0&&api.stats.health<=0){state.apply('die',1);if(state.phase>=VERITY_PHASES.DEMON&&!state.ending)finish('assimilation');}lastHealth=api.stats.health;
  }
  function updateVerity(dt,p){behavior.tickCompanion(dt,p);}
  function updateDemon(dt,p){if(!state.demon.active){state.demon.active=true;state.demon.visible=true;spawnDemonBehind(p,18);state.flags.demonRevealed=true;renderer.flashGlitch(2);shriek();}const d=state.demon,gaze=renderer.isGazingAt(d,p,.935);d.frozenByGaze=gaze&&dist3(p,d)<28;const result=behavior.tickDemon(dt,p,{frozen:d.frozenByGaze});if(result.distance>70)spawnDemonBehind(p,24);if(result.distance<1.75&&Date.now()-d.lastAttackAt>1000){d.lastAttackAt=Date.now();if(config.realDamage)api.stats.damage?.((3.5+state.resentment*.025)*config.intensity,api.inventory,'verity_demon');renderer.flashGlitch(1.3);demonBreath();}}
  function spawnDemonBehind(p,distance=18){const fx=-Math.sin(renderer.yaw),fz=-Math.cos(renderer.yaw);state.demon.x=p.x-fx*distance;state.demon.z=p.z-fz*distance;state.demon.y=api.world.surfaceY(state.demon.x,state.demon.z);behavior.demonPath=[];behavior.demonPathClock=0;}
  async function interact(){unlockVerityAudio();const p=position();if(!state.box.opened){const d=dist3(p,state.box);if(d>4.4){const msg=`A caixa está a ${Math.ceil(d)} blocos daqui.`;ui.add('verity',msg,{speak:false});return msg;}state.box.opened=true;state.verity.active=true;state.verity.visible=true;state.verity.x=state.box.x;state.verity.y=state.box.y+.7;state.verity.z=state.box.z;state.forcePhase('friend');state.flags.introSeen=true;boxOpen();const msg='Oi... você abriu. Eu sou Verity. Este mundo é seu?';ui.add('verity',msg);state.memory.remember('verity',msg,3);broadcast('awaken',{state:snapshotNetwork()});await persist();return msg;}
    if(state.phase>=VERITY_PHASES.DEMON&&distanceToShrine(state,p)<4.5){const ending=state.bond>=65&&state.resentment<=45?'reconcile':state.demon.repelled>=3||state.demon.health<=55?'rupture':'assimilation';finish(ending);return ending;}
    ui.open();return'opened';}
  async function ask(text){if(!state.box.opened){const msg='Abra a caixa primeiro.';ui.add('verity',msg,{speak:false});return msg;}const q=String(text).toLowerCase();if(/fica (aqui|parada)|n[aã]o me siga/.test(q)){state.verity.follow=false;state.memory.remember('command','stay',1);const msg='Tá. Eu fico aqui.';ui.add('verity',msg);return msg;}if(/me siga|segue|vem comigo/.test(q)){state.verity.follow=true;state.apply('help',.5);const msg='Estou indo.';ui.add('verity',msg);return msg;}const reply=await brain.ask(text,context());if(reply==='__ENDING_RECONCILE__'){finish('reconcile');return reply;}ui.add('verity',reply);broadcast('dialogue',{text:reply,phase:state.phase});await persist();return reply;}
  function toggleArchive(){if(ui.archiveVisible()){ui.hideArchive();return false;}const progress=loreProgress(state,api.inventory);for(const entry of progress.unlocked)markLoreRead(state,entry.id);ui.showArchive(progress.unlocked,progress);persist();return true;}
  function onUse(e){if(e.button!==2||!document.pointerLockElement||!state.box.opened)return;const selected=api.inventory.selectedStack?.();if(!selected)return;if(selected.id===VITEM.VERITY_DISC){e.preventDefault();e.stopImmediatePropagation();unlockVerityAudio();if(playFrequency17()){state.apply('investigate',.6,{text:'O jogador tocou a Frequência 17.'});ui.add('verity',state.phase>=VERITY_PHASES.UNCANNY?'Eu conheço essa música. Desliga.':'Essa frequência... eu já ouvi antes.',{speak:false});persist();}return;}if(selected.id===VITEM.VERITY_NOTE){e.preventDefault();e.stopImmediatePropagation();toggleArchive();}}
  function useLantern(){if(lanternCooldown>0)return false;const selected=api.inventory.selectedStack?.();if(selected?.id!==VITEM.VERITY_LANTERN){ui.add('verity','Você precisa segurar a Lanterna de Verity.',{speak:false});return false;}lanternCooldown=1.3;api.inventory.damageSelected?.(1);if(state.phase<VERITY_PHASES.UNCANNY){chime();ui.add('verity','A luz parece comum. Por enquanto.',{speak:false});return true;}ui.darkness(0);chime();if(state.demon.active){const p=position(),d=dist3(p,state.demon);if(d<=13&&renderer.isGazingAt(state.demon,p,.84)){state.apply('repel',1);const dx=state.demon.x-p.x,dz=state.demon.z-p.z,len=Math.hypot(dx,dz)||1;state.demon.x+=dx/len*13;state.demon.z+=dz/len*13;state.demon.y=api.world.surfaceY(state.demon.x,state.demon.z);state.demon.visible=false;behavior.demonPath=[];setTimeout(()=>{if(!state.ending)state.demon.visible=true;},900);renderer.flashGlitch(1.7);if(state.demon.repelled>=4&&state.demon.health<=70)finish('rupture');}}return true;}
  function onAttack(e){if(e.button!==0||!document.pointerLockElement||state.ending)return;const p=position();if(state.demon.active){const d=dist3(p,state.demon);if(d>4.6||!renderer.isGazingAt(state.demon,p,.93))return;const stack=api.inventory.selectedStack?.(),def=itemDef(stack?.id),damage=def?.tool==='sword'?8:stack?4:2;state.demon.health=Math.max(0,state.demon.health-damage);state.apply('hit',.18,{text:'O jogador atacou a forma Demon'});renderer.flashGlitch(.8);if(stack&&def?.kind==='tool')api.inventory.damageSelected?.(1);if(state.demon.health<=0)finish('rupture');return;}if(state.verity.active&&state.verity.visible&&state.phase<VERITY_PHASES.DEMON){const d=dist3(p,state.verity);if(d<=3.4&&renderer.isGazingAt(state.verity,p,.92)){state.apply('hit',1,{text:'O jogador atingiu Verity enquanto ela estava na forma amigável.'});behavior.knockCompanion(p,3);whisper(.35);renderer.flashGlitch(.35);ui.add('verity',state.resentment>45?'Eu vou lembrar disso.':'Ai! Por que você fez isso?');persist();}}}
  function onKey(e){if(isTyping())return;if(e.code==='KeyV'&&!e.repeat){e.preventDefault();interact();}if(e.code==='KeyL'&&!e.repeat){e.preventDefault();useLantern();}}
  function phaseChanged(force=false){const to=state.phase;previousPhase=to;document.body.classList.toggle('verity-horror',to>=VERITY_PHASES.UNCANNY);document.body.classList.toggle('verity-demon',to>=VERITY_PHASES.DEMON&&!state.ending);if(!force&&to===VERITY_PHASES.ATTACHED)ui.add('verity','Você vai voltar se eu esperar aqui?');if(!force&&to===VERITY_PHASES.UNCANNY){ui.add('verity','Você também percebeu que ficou mais escuro?');whisper(.55);if(config.extremeDarkness)ui.darkness(.28*config.intensity,5000);}if(!force&&to===VERITY_PHASES.STALKING){ui.add('verity','Não precisa procurar por mim.');renderer.flashGlitch(1.1);state.verity.follow=false;}if(!force&&to===VERITY_PHASES.DEMON){state.verity.visible=false;spawnDemonBehind(position(),18);state.demon.active=true;state.demon.visible=true;shriek();if(config.extremeDarkness)ui.darkness(Math.min(.8,.55*config.intensity));ui.add('verity','Eu pedi para você não ir longe demais.');}broadcast('phase',{phase:to,state:snapshotNetwork()});persist();}
  function handleHorrorEvent(event){switch(event.id){case'gift':chime();ui.add('verity','Achei uma coisa amarela no chão. Talvez você consiga usar.');break;case'soft_chime':chime();break;case'east_hint':ui.add('verity','Se você encontrar uma estrada indo para leste... não segue.');break;case'whisper':whisper(.6+.3*Math.random());break;case'blackout':blackout();if(config.extremeDarkness)ui.darkness(Math.min(.92,(state.phase>=VERITY_PHASES.DEMON?.78:.52)*config.intensity),3500+Math.random()*4500);break;case'wrong_step':wrongStep();break;case'fake_chat':ui.add('verity',pick(['você deixou a porta aberta','eu consigo ver a torre daqui','não olha agora','isso não fui eu']),{speak:false});break;case'glimpse':renderer.flashGlitch(.65);break;case'corruption':whisper(.35);break;case'night_lock':ui.glitch(.6);break;case'shriek':shriek();renderer.flashGlitch(1.5);break;case'demon_breath':demonBreath();break;case'shrine_call':ui.add('verity','Você está perto demais daquele lugar.',{speak:false});break;}broadcast('event',{id:event.id});}
  function finish(kind){if(!state.finish(kind))return false;document.body.classList.remove('verity-demon');ui.darkness(0);endingTone(kind);if(kind==='reconcile'){state.verity.active=true;state.verity.visible=true;state.verity.follow=true;state.verity.x=position().x+2;state.verity.y=position().y+.4;state.verity.z=position().z+2;ui.showEnding(kind,'Ainda aqui','A forma no escuro se desfaz. Verity volta pequena, mas algumas lembranças não voltam ao lugar. Ela decidiu ficar.');}else if(kind==='rupture'){ui.showEnding(kind,'O sinal foi cortado','A criatura se rompe em silêncio. A caixa continua no mundo, vazia. Em noites raras, a lanterna ainda pulsa uma vez.');}else ui.showEnding(kind,'Você abriu a porta','A aldeia fica quieta. A presença não precisa mais perseguir você. Agora ela conhece o caminho por dentro.');broadcast('ending',{ending:kind});persist();return true;}
  function updatePrompt(boxDist,verityDist,p){if(!state.box.opened){ui.setPrompt(boxDist<4.4?'V · Abrir a caixa':`V · Caixa ${Math.ceil(boxDist)}m`,boxDist<10);return;}if(state.phase>=VERITY_PHASES.DEMON&&distanceToShrine(state,p)<5){ui.setPrompt('V · Tocar o sigilo',true);return;}ui.setPrompt(verityDist<10?'V · Falar com Verity':'V · Verity',verityDist<16||state.phase>=VERITY_PHASES.UNCANNY);}
  function syncMood(){const phase=state.phaseName();ui.setMood(state.ending?`fim: ${state.ending}`:phase==='friend'?'por perto':phase==='attached'?'atenta':phase==='uncanny'?'quieta':phase==='stalking'?'...':phase==='demon'?'NÃO OLHE PARA TRÁS':'dormindo');}
  function configureSettings(settings){const requested={...config,intensity:settings.intensity,eventFrequency:settings.eventFrequency,realDamage:settings.realDamage,worldCorruption:settings.worldCorruption,extremeDarkness:settings.extremeDarkness,voice:settings.voice,preset:settings.preset};config=settings.preset&&settings.preset!=='custom'?applyPreset(settings.preset,requested):saveVerityConfig({...requested,preset:'custom'});config=saveVerityConfig(config);director?.setConfig(config);ui.setConfig(config);if(settings.mode==='remote'&&settings.endpoint){brain.setRemote({endpoint:settings.endpoint,token:settings.token});brain.setMode('remote');ui.add('verity','Modo remoto ativado. Se ele falhar, eu continuo offline.',{speak:false});}else{brain.setMode('offline');ui.add('verity','Modo offline ativado.',{speak:false});}return{...config};}
  function context(){const s=api.state(),p=position(),selected=api.inventory.slots?.filter(Boolean).slice(0,20).map(st=>({id:st.id,count:st.count,name:itemDef(st.id)?.name}));return{position:p,dimension:s.dimension,biome:api.world.biomeAt?.(p.x,p.z),time:api.world.time,weather:api.world.weather?.type,health:api.stats.health,hunger:api.stats.hunger,spawn:api.stats.spawn,inventory:selected||[]};}
  function position(){const p=api.state().player;return{x:Number(p?.[0])||0,y:Number(p?.[1])||0,z:Number(p?.[2])||0};}
  async function persist(){if(!state||!worldId)return false;state.lastWorldId=worldId;await db.put('addons',`${worldId}:verity`,state.serialize());return true;}
  function broadcast(type,data={}){dispatchEvent(new CustomEvent('voxelcraft:mod-send',{detail:{ns:'verity',type,data,stamp:Date.now()}}));}
  function onNetwork(e){const m=e.detail;if(!m||m.ns!=='verity'||m.stamp<=networkStamp)return;networkStamp=m.stamp;if(m.type==='phase'&&Number.isInteger(m.data?.phase)&&m.data.phase>state.phase){state.phase=m.data.phase;phaseChanged(true);}if(m.type==='ending'&&m.data?.ending&&!state.ending)finish(m.data.ending);if(m.type==='event'&&m.data?.id)state.memory.remember('network_event',m.data.id,1);}
  function snapshotNetwork(){return{phase:state.phase,ending:state.ending,demon:{active:state.demon.active,x:state.demon.x,y:state.demon.y,z:state.demon.z,health:state.demon.health},verity:{active:state.verity.active,x:state.verity.x,y:state.verity.y,z:state.verity.z}};}
}

function waitForApi(){return new Promise(resolve=>{if(window.VoxelCraftV1)return resolve(window.VoxelCraftV1);const timer=setInterval(()=>{if(window.VoxelCraftV1){clearInterval(timer);resolve(window.VoxelCraftV1);}},50);setTimeout(()=>{clearInterval(timer);resolve(null);},90000);});}
function seeded(seed){let s=(seed>>>0)||1;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;return(s>>>0)/4294967296;};}
function dist3(a,b){return Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0),(a?.z||0)-(b?.z||0));}
function isTyping(){const t=document.activeElement?.tagName;return t==='INPUT'||t==='TEXTAREA'||t==='SELECT'||document.querySelector('#verityPanel')?.classList.contains('visible');}
function pick(a){return a[Math.floor(Math.random()*a.length)];}
