import * as THREE from 'three';
import { VERITY_PHASES } from './state.js';
import { observeMainScene } from '../../v1/scene-hook.js';

export class VerityRenderer{
  constructor(){
    this.mainRenderer=window.VoxelCraftV1?.renderer||null;this.scene=null;this.camera=null;this.time=0;this.lastPhase=-1;this.glitch=0;this.quality=window.VoxelCraftPerformance?.current||{effects:1,mode:'auto'};
    this.root=new THREE.Group();this.root.name='verity-native-root';this.box=createBox();this.friend=createFriend();this.demon=createDemon();this.root.add(this.box,this.friend,this.demon);
    this.friendGlow=this.friend.getObjectByName('verity-glow');this.demonGlow=this.demon.getObjectByName('verity-demon-glow');
    this.offScene=this.mainRenderer?observeMainScene(this.mainRenderer,(scene,camera)=>this.attach(scene,camera)):()=>{};
    this.onPerformance=(e)=>{this.quality=e.detail||this.quality;this.applyQuality();};addEventListener('voxelcraft:performance-profile',this.onPerformance);this.applyQuality();
  }
  attach(scene,camera){if(this.scene!==scene){if(this.scene)this.scene.remove(this.root);this.scene=scene;scene.add(this.root);}this.camera=camera;}
  applyQuality(){const effects=Math.max(.35,Number(this.quality?.effects)||1);if(this.friendGlow)this.friendGlow.intensity=effects<.65?0:.55*effects;if(this.demonGlow)this.demonGlow.intensity=effects<.58?0:1.15*effects;}
  update(state,player,dt){
    this.time+=dt;
    this.box.visible=state.box.spawned&&!state.box.opened;setWorld(this.box,state.box);this.box.rotation.y=Math.sin(this.time*.5)*.03;
    this.friend.visible=state.verity.active&&state.verity.visible&&state.phase<VERITY_PHASES.DEMON&&!state.ending;setWorld(this.friend,state.verity);this.friend.position.y=state.verity.y+Math.abs(Math.sin(this.time*3.1))*.25;if(this.camera)this.friend.rotation.y=faceYaw(this.friend.position,this.camera.position);const ball=this.friend.getObjectByName('verity-ball');if(ball)ball.rotation.z=Math.sin(this.time*2.2)*.035;
    this.demon.visible=Boolean(state.demon.visible||state.demon.active)&&!state.ending;setWorld(this.demon,state.demon);if(this.camera)this.demon.rotation.y=faceYaw(this.demon.position,this.camera.position);animateDemon(this.demon,this.time,state);
    const maxDistance=this.quality?.mode==='low'?72:110;if(this.camera){this.friend.visible=this.friend.visible&&this.friend.position.distanceToSquared(this.camera.position)<maxDistance*maxDistance;this.box.visible=this.box.visible&&this.box.position.distanceToSquared(this.camera.position)<maxDistance*maxDistance;this.demon.visible=this.demon.visible&&this.demon.position.distanceToSquared(this.camera.position)<(maxDistance+30)*(maxDistance+30);}
    if(state.phase!==this.lastPhase){this.lastPhase=state.phase;this.glitch=state.phase>=VERITY_PHASES.UNCANNY?1:0;}
  }
  gazeScore(target,player){if(!this.camera)return-1;const lift=target?.maxHealth?1.45:.35,targetY=(Number(target?.y)||0)+lift,v=new THREE.Vector3((Number(target?.x)||0)-this.camera.position.x,targetY-this.camera.position.y,(Number(target?.z)||0)-this.camera.position.z);if(v.lengthSq()<.0001)return 1;v.normalize();const look=new THREE.Vector3();this.camera.getWorldDirection(look);return look.dot(v);}
  isGazingAt(target,player,threshold=.94){return this.gazeScore(target,player)>=threshold;}
  distanceFromCrosshair(target,player){return 1-this.gazeScore(target,player);}
  get yaw(){return this.camera?.rotation?.y||0;}
  get pitch(){return this.camera?.rotation?.x||0;}
  flashGlitch(strength=1){const canvas=this.mainRenderer?.domElement||document.querySelector('#game');canvas?.animate?.([{filter:'none',transform:'translate(0,0)'},{filter:`contrast(${1+strength}) saturate(.2)`,transform:`translate(${strength*3}px,${-strength*2}px)`},{filter:'none',transform:'none'}],{duration:140+strength*80,iterations:2});}
  dispose(){removeEventListener('voxelcraft:performance-profile',this.onPerformance);this.offScene?.();if(this.scene)this.scene.remove(this.root);disposeObject(this.root);this.scene=null;this.camera=null;}
}

function setWorld(obj,target){obj.position.set(Number(target?.x)||0,Number(target?.y)||0,Number(target?.z)||0);}
function faceYaw(from,to){return Math.atan2(to.x-from.x,to.z-from.z)+Math.PI;}
function createBox(){const g=new THREE.Group(),card=new THREE.MeshLambertMaterial({color:0x9b7045}),lidMat=new THREE.MeshLambertMaterial({color:0xb08152});const base=new THREE.Mesh(new THREE.BoxGeometry(1.15,.85,1.05),card);base.position.y=.42;g.add(base);const lid=new THREE.Mesh(new THREE.BoxGeometry(1.22,.12,1.12),lidMat);lid.position.set(0,.92,-.08);lid.rotation.x=-.1;g.add(lid);const mark=makeFacePlane('?',0x2b221b,.36);mark.position.set(0,.48,.531);g.add(mark);g.name='verity-box';return g;}
function createFriend(){const root=new THREE.Group(),yellow=new THREE.MeshLambertMaterial({color:0xf3d22d}),eyeMat=new THREE.MeshBasicMaterial({color:0x191711}),ball=new THREE.Mesh(new THREE.SphereGeometry(.48,20,12),yellow);ball.name='verity-ball';root.add(ball);for(const x of[-.15,.15]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.045,8,6),eyeMat);eye.position.set(x,.09,-.459);root.add(eye);}const mouth=new THREE.Mesh(new THREE.TorusGeometry(.105,.018,6,14,Math.PI),eyeMat);mouth.position.set(0,-.06,-.46);mouth.rotation.set(0,0,Math.PI);root.add(mouth);const glow=new THREE.PointLight(0xffd92f,.55,2.8);glow.name='verity-glow';glow.position.set(0,.1,0);root.add(glow);root.name='verity-friend';return root;}
function createDemon(){const root=new THREE.Group(),skin=new THREE.MeshLambertMaterial({color:0x171419}),bone=new THREE.MeshLambertMaterial({color:0x393037}),eye=new THREE.MeshBasicMaterial({color:0xffd91f});const torso=new THREE.Mesh(new THREE.BoxGeometry(.78,2.05,.48),skin);torso.position.y=1.3;root.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.43,14,9),skin);head.scale.set(1,.82,.9);head.position.y=2.62;root.add(head);for(const x of[-.15,.15]){const e=new THREE.Mesh(new THREE.SphereGeometry(.05,7,5),eye);e.position.set(x,2.67,-.385);root.add(e);}const jaw=new THREE.Mesh(new THREE.BoxGeometry(.42,.12,.08),bone);jaw.position.set(0,2.4,-.39);root.add(jaw);for(const side of[-1,1]){const armPivot=new THREE.Group();armPivot.position.set(side*.53,2.03,0);const arm=new THREE.Mesh(new THREE.CylinderGeometry(.095,.07,2.7,6),skin);arm.position.y=-1.15;armPivot.add(arm);const claw=new THREE.Mesh(new THREE.ConeGeometry(.16,.65,5),bone);claw.position.y=-2.62;armPivot.add(claw);root.add(armPivot);armPivot.name=side<0?'armL':'armR';const leg=new THREE.Mesh(new THREE.CylinderGeometry(.13,.1,1.8,6),skin);leg.position.set(side*.22,-.55,0);root.add(leg);}const aura=new THREE.PointLight(0xffcf21,1.15,4.6);aura.name='verity-demon-glow';aura.position.y=2.2;root.add(aura);root.scale.setScalar(1.07);root.name='verity-demon';return root;}
function animateDemon(root,t,state){const a=root.getObjectByName('armL'),b=root.getObjectByName('armR'),speed=state.phase>=VERITY_PHASES.DEMON?5:2;if(a)a.rotation.x=Math.sin(t*speed)*.24-.18;if(b)b.rotation.x=-Math.sin(t*speed)*.24-.18;root.position.y=(Number(state.demon?.y)||0)+Math.sin(t*1.8)*.025;}
function makeFacePlane(text,color,size){const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d');x.clearRect(0,0,64,64);x.fillStyle=`#${color.toString(16).padStart(6,'0')}`;x.font='bold 46px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(text,32,35);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const m=new THREE.MeshBasicMaterial({map:tex,transparent:true});return new THREE.Mesh(new THREE.PlaneGeometry(size,size),m);}
function disposeObject(root){const disposedG=new Set(),disposedM=new Set();root.traverse((o)=>{if(o.geometry&&!disposedG.has(o.geometry)){disposedG.add(o.geometry);o.geometry.dispose();}const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if(!m||disposedM.has(m))continue;disposedM.add(m);m.map?.dispose?.();m.dispose?.();}});}
