import * as THREE from 'three';
import { VERITY_PHASES } from './state.js';

export class VerityRenderer{
  constructor(){
    this.canvas=document.createElement('canvas');this.canvas.id='verityCanvas';this.canvas.setAttribute('aria-hidden','true');document.body.appendChild(this.canvas);
    this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,alpha:true,antialias:true,powerPreference:'high-performance'});this.renderer.setClearColor(0x000000,0);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));
    this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.05,220);this.camera.rotation.order='YXZ';
    this.scene.add(new THREE.HemisphereLight(0xfff8c8,0x18141a,1.7));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(-2,5,3);this.scene.add(light);
    this.box=createBox();this.friend=createFriend();this.demon=createDemon();this.scene.add(this.box,this.friend,this.demon);this.yaw=0;this.pitch=0;this.time=0;this.lastPhase=-1;this.glitch=0;
    this.onMouse=(e)=>{if(document.pointerLockElement){this.yaw-=e.movementX*.002;this.pitch=Math.max(-1.54,Math.min(1.54,this.pitch-e.movementY*.002));}};this.onResize=()=>this.resize();addEventListener('mousemove',this.onMouse);addEventListener('resize',this.onResize);this.resize();
  }
  resize(){this.camera.aspect=innerWidth/Math.max(1,innerHeight);this.camera.updateProjectionMatrix();this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.setSize(innerWidth,innerHeight,false);}
  update(state,player,dt){this.time+=dt;this.camera.rotation.set(this.pitch,this.yaw,0);const eyeY=player.y+1.62;
    this.box.visible=state.box.spawned&&!state.box.opened;setRelative(this.box,state.box,player,eyeY);this.box.rotation.y=Math.sin(this.time*.5)*.03;
    this.friend.visible=state.verity.active&&state.verity.visible&&state.phase<VERITY_PHASES.DEMON&&!state.ending;setRelative(this.friend,state.verity,player,eyeY);this.friend.position.y+=Math.abs(Math.sin(this.time*3.1))*.25;this.friend.rotation.y=this.yaw+Math.PI;this.friend.children[0].rotation.z=Math.sin(this.time*2.2)*.035;
    this.demon.visible=Boolean(state.demon.visible||state.demon.active)&&!state.ending;setRelative(this.demon,state.demon,player,eyeY);this.demon.rotation.y=this.yaw+Math.PI;animateDemon(this.demon,this.time,state);
    if(state.phase!==this.lastPhase){this.lastPhase=state.phase;this.glitch=state.phase>=VERITY_PHASES.UNCANNY?1:0;}
    this.renderer.render(this.scene,this.camera);
  }
  gazeScore(target,player){const v=new THREE.Vector3(target.x-player.x,target.y-(player.y+1.62),target.z-player.z).normalize(),look=new THREE.Vector3(0,0,-1).applyEuler(this.camera.rotation);return look.dot(v);}
  isGazingAt(target,player,threshold=.94){return this.gazeScore(target,player)>=threshold;}
  distanceFromCrosshair(target,player){return 1-this.gazeScore(target,player);}
  flashGlitch(strength=1){this.canvas.animate([{filter:'none',transform:'translate(0,0)'},{filter:`contrast(${1+strength}) saturate(.2)`,transform:`translate(${strength*3}px,${-strength*2}px)`},{filter:'none',transform:'none'}],{duration:140+strength*80,iterations:2});}
  dispose(){removeEventListener('mousemove',this.onMouse);removeEventListener('resize',this.onResize);for(const root of[this.box,this.friend,this.demon])disposeObject(root);this.renderer.dispose();this.canvas.remove();}
}

function setRelative(obj,target,player,eyeY){obj.position.set(target.x-player.x,target.y-eyeY,target.z-player.z);}
function createBox(){const g=new THREE.Group(),card=new THREE.MeshStandardMaterial({color:0x9b7045,roughness:1});const base=new THREE.Mesh(new THREE.BoxGeometry(1.15,.85,1.05),card);base.position.y=.42;g.add(base);const lid=new THREE.Mesh(new THREE.BoxGeometry(1.22,.12,1.12),new THREE.MeshStandardMaterial({color:0xb08152,roughness:1}));lid.position.set(0,.92,-.08);lid.rotation.x=-.1;g.add(lid);const mark=makeFacePlane('?',0x2b221b,.36);mark.position.set(0,.48,.531);g.add(mark);return g;}
function createFriend(){const root=new THREE.Group(),ball=new THREE.Mesh(new THREE.SphereGeometry(.48,32,20),new THREE.MeshStandardMaterial({color:0xf3d22d,roughness:.55,metalness:0}));ball.name='verity-ball';root.add(ball);const eyeMat=new THREE.MeshBasicMaterial({color:0x191711});for(const x of[-.15,.15]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.045,12,8),eyeMat);eye.position.set(x,.09,-.459);root.add(eye);}const mouth=new THREE.Mesh(new THREE.TorusGeometry(.105,.018,8,18,Math.PI),eyeMat);mouth.position.set(0,-.06,-.46);mouth.rotation.set(0,0,Math.PI);root.add(mouth);const glow=new THREE.PointLight(0xffd92f,.7,3);glow.position.set(0,.1,0);root.add(glow);return root;}
function createDemon(){const root=new THREE.Group(),skin=new THREE.MeshStandardMaterial({color:0x171419,roughness:.92}),bone=new THREE.MeshStandardMaterial({color:0x393037,roughness:1}),eye=new THREE.MeshBasicMaterial({color:0xffd91f});const torso=new THREE.Mesh(new THREE.BoxGeometry(.78,2.05,.48),skin);torso.position.y=1.3;root.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.43,18,12),skin);head.scale.set(1,.82,.9);head.position.y=2.62;root.add(head);for(const x of[-.15,.15]){const e=new THREE.Mesh(new THREE.SphereGeometry(.05,10,6),eye);e.position.set(x,2.67,-.385);root.add(e);}const jaw=new THREE.Mesh(new THREE.BoxGeometry(.42,.12,.08),bone);jaw.position.set(0,2.4,-.39);root.add(jaw);for(const side of[-1,1]){const armPivot=new THREE.Group();armPivot.position.set(side*.53,2.03,0);const arm=new THREE.Mesh(new THREE.CylinderGeometry(.095,.07,2.7,8),skin);arm.position.y=-1.15;armPivot.add(arm);const claw=new THREE.Mesh(new THREE.ConeGeometry(.16,.65,6),bone);claw.position.y=-2.62;armPivot.add(claw);root.add(armPivot);armPivot.name=side<0?'armL':'armR';const leg=new THREE.Mesh(new THREE.CylinderGeometry(.13,.1,1.8,8),skin);leg.position.set(side*.22,-.55,0);root.add(leg);}const aura=new THREE.PointLight(0xffcf21,1.8,5);aura.position.y=2.2;root.add(aura);root.scale.setScalar(1.07);return root;}
function animateDemon(root,t,state){const a=root.getObjectByName('armL'),b=root.getObjectByName('armR'),speed=state.phase>=VERITY_PHASES.DEMON?5:2;if(a)a.rotation.x=Math.sin(t*speed)*.24-.18;if(b)b.rotation.x=-Math.sin(t*speed)*.24-.18;root.position.y+=Math.sin(t*1.8)*.025;}
function makeFacePlane(text,color,size){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.clearRect(0,0,128,128);x.fillStyle=`#${color.toString(16).padStart(6,'0')}`;x.font='bold 92px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(text,64,70);const tex=new THREE.CanvasTexture(c),m=new THREE.MeshBasicMaterial({map:tex,transparent:true});return new THREE.Mesh(new THREE.PlaneGeometry(size,size),m);}
function disposeObject(root){root.traverse(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>{m.map?.dispose?.();m.dispose?.();});else{o.material?.map?.dispose?.();o.material?.dispose?.();}});}
