import { BLOCK } from '../../v1/catalog.js';
import { VBLOCK, VITEM } from './content.js';

export function initializeVerityLandmarks(world,state,player){if(state.eastVillage.x||state.eastVillage.z)return state.eastVillage;const seed=(world.seed||state.seed||1)>>>0,offset=150+(seed%55),side=((seed>>>4)%61)-30;state.eastVillage.x=Math.floor(player.x+offset);state.eastVillage.z=Math.floor(player.z+side);state.eastVillage.towerX=state.eastVillage.x+34;state.eastVillage.towerZ=state.eastVillage.z-20;state.eastVillage.shrineX=state.eastVillage.x-28;state.eastVillage.shrineZ=state.eastVillage.z+24;return state.eastVillage;}
export function maybeGenerateLandmarks(world,state,player,{radius=130}={}){const v=state.eastVillage;if(!v.x&&!v.z)initializeVerityLandmarks(world,state,player);const d=Math.hypot(player.x-v.x,player.z-v.z);if(!v.generated&&d<=radius){generateEastVillage(world,state);return true;}return false;}
export function generateEastVillage(world,state){const v=state.eastVillage;if(v.generated)return false;const homes=[[0,0],[14,5],[-13,7],[7,-15],[-15,-11]];for(let i=0;i<homes.length;i++){const[dx,dz]=homes[i];buildAbandonedHouse(world,v.x+dx,v.z+dz,i);}buildLookoutTower(world,v.towerX,v.towerZ);v.shrineY=buildShrine(world,v.shrineX,v.shrineZ);buildPath(world,v.x,v.z,v.towerX,v.towerZ);buildPath(world,v.x,v.z,v.shrineX,v.shrineZ);v.generated=true;state.memory.remember('world','A aldeia a leste foi gerada.',5,{x:v.x,z:v.z,shrineY:v.shrineY});return true;}
function buildAbandonedHouse(world,cx,cz,index){const y=surface(world,cx,cz);for(let x=-4;x<=4;x++)for(let z=-3;z<=3;z++){set(world,cx+x,y-1,cz+z,index%2?BLOCK.COBBLE:VBLOCK.PALE_BRICKS);for(let dy=0;dy<=3;dy++){const edge=Math.abs(x)===4||Math.abs(z)===3;if(edge)set(world,cx+x,y+dy,cz+z,dy===0?BLOCK.LOG:BLOCK.PLANKS);}set(world,cx+x,y+4,cz+z,BLOCK.PLANKS);}for(let dy=0;dy<2;dy++)set(world,cx,y+dy,cz+3,BLOCK.AIR);set(world,cx-2,y+1,cz-3,BLOCK.GLASS);set(world,cx+2,y+1,cz-3,BLOCK.GLASS);set(world,cx+2,y,cz+1,BLOCK.CHEST);set(world,cx-2,y,cz+1,BLOCK.BED);if(index===0){set(world,cx,y,cz-1,VBLOCK.VERITY_SIGIL);putLoot(world,cx+2,y,cz+1,[{id:VITEM.VERITY_NOTE,count:1},{id:VITEM.VERITY_SHARD,count:1}]);}else putLoot(world,cx+2,y,cz+1,[{id:VITEM.VERITY_NOTE,count:1}]);}
function buildLookoutTower(world,cx,cz){const y=surface(world,cx,cz);for(let dy=0;dy<13;dy++)for(let x=-2;x<=2;x++)for(let z=-2;z<=2;z++){const edge=Math.abs(x)===2||Math.abs(z)===2;if(edge)set(world,cx+x,y+dy,cz+z,dy%3===0?BLOCK.COBBLE:VBLOCK.PALE_BRICKS);}for(let dy=0;dy<12;dy++)set(world,cx+1,y+dy,cz+1,BLOCK.LADDER);for(let x=-3;x<=3;x++)for(let z=-3;z<=3;z++)set(world,cx+x,y+13,cz+z,VBLOCK.PALE_BRICKS);set(world,cx,y+14,cz,VBLOCK.VERITY_SIGIL);set(world,cx+1,y+14,cz,BLOCK.TORCH);}
function buildShrine(world,cx,cz){const y=surface(world,cx,cz);for(let x=-5;x<=5;x++)for(let z=-5;z<=5;z++)if(Math.hypot(x,z)<=5.2)set(world,cx+x,y-1,cz+z,VBLOCK.CORRUPTED_STONE);for(let dy=0;dy<5;dy++){set(world,cx-3,y+dy,cz,VBLOCK.PALE_BRICKS);set(world,cx+3,y+dy,cz,VBLOCK.PALE_BRICKS);}for(let x=-3;x<=3;x++)set(world,cx+x,y+4,cz,VBLOCK.PALE_BRICKS);set(world,cx,y,cz,VBLOCK.VERITY_SIGIL);set(world,cx,y+1,cz,VBLOCK.OBSERVER_GLASS);set(world,cx,y,cz-2,BLOCK.CHEST);putLoot(world,cx,y,cz-2,[{id:VITEM.VERITY_SHARD,count:3},{id:VITEM.VERITY_DISC,count:1},{id:VITEM.VERITY_NOTE,count:2}]);return y;}
function buildPath(world,ax,az,bx,bz){const steps=Math.ceil(Math.hypot(bx-ax,bz-az));for(let i=0;i<=steps;i++){const t=i/Math.max(1,steps),x=Math.round(ax+(bx-ax)*t),z=Math.round(az+(bz-az)*t),y=surface(world,x,z);set(world,x,y-1,z,i%7===0?VBLOCK.CORRUPTED_STONE:BLOCK.COBBLE);}}
export function corruptPatch(world,x,z,{radius=4,intensity=.38}={}){let changed=0;for(let dx=-radius;dx<=radius;dx++)for(let dz=-radius;dz<=radius;dz++){if(Math.hypot(dx,dz)>radius||hash(x+dx,z+dz)<1-intensity)continue;const y=surface(world,x+dx,z+dz),id=world.getBlock(x+dx,y-1,z+dz);if(id!==BLOCK.BEDROCK&&id!==BLOCK.AIR){set(world,x+dx,y-1,z+dz,VBLOCK.CORRUPTED_STONE);changed++;}}return changed;}
export function placeVerityMark(world,x,z){const y=surface(world,x,z);set(world,x,y,z,VBLOCK.VERITY_SIGIL);return{x,y,z};}
export function distanceToShrine(state,p){return Math.hypot(p.x-state.eastVillage.shrineX,p.z-state.eastVillage.shrineZ);}
function putLoot(world,x,y,z,items){world.blockEntities.set(`${x},${y},${z}`,{type:'chest',inventory:{size:27,slots:[...items,...Array(Math.max(0,27-items.length)).fill(null)],hotbar:[0,1,2,3,4,5,6,7,8],selected:0,armor:{head:null,chest:null,legs:null,feet:null},offhand:null}});}
function surface(world,x,z){return Math.max(2,Math.min(92,Math.floor(world.surfaceY(x+.5,z+.5))));}
function set(world,x,y,z,id){if(y<0||y>=96)return false;return world.setBlock(Math.floor(x),Math.floor(y),Math.floor(z),id,{track:true});}
function hash(x,z){let h=Math.imul(x|0,374761393)^Math.imul(z|0,668265263);h=(h^(h>>>13))*1274126177;return((h^(h>>>16))>>>0)/4294967295;}
