import * as THREE from 'three';
import { observeMainScene } from './scene-hook.js';

const waitForApi=()=>new Promise((resolve)=>{if(window.VoxelCraftV1)return resolve(window.VoxelCraftV1);const timer=setInterval(()=>{if(window.VoxelCraftV1){clearInterval(timer);resolve(window.VoxelCraftV1);}},50);setTimeout(()=>{clearInterval(timer);resolve(null);},90_000);});
const api=await waitForApi();
if(api)boot(api);

function boot(api){
  const renderer=api.renderer,hardware=detectHardware(renderer),stored=loadJson('voxelcraft-v1-settings',{});
  let userCeiling=clamp(Number(stored.resolutionScale)||1.5,.65,2),userRenderDistance=clamp(Number(stored.renderDistance)||3,2,6),mode=localStorage.getItem('voxelcraft-performance-profile')||'auto',scene=null,camera=null,currentScale=Math.min(userCeiling,initialScale(mode,hardware,userCeiling)),lowStreak=0,highStreak=0,lastApply=0,lastFps=0;
  const offScene=observeMainScene(renderer,(nextScene,nextCamera)=>{scene=nextScene;camera=nextCamera;applySceneBudget();});
  installUI();applyMode(true);
  const timer=setInterval(sample,2500);
  addEventListener('resize',()=>setTimeout(()=>applyScale(currentScale,true),0));
  addEventListener('beforeunload',()=>{clearInterval(timer);offScene();},{once:true});
  window.VoxelCraftPerformance={get current(){return snapshot();},setProfile:setMode,detect:()=>({...hardware}),reapply:()=>applyMode(true)};

  function sample(){const fps=Number(api.state?.().fps)||0;if(!fps)return;lastFps=fps;if(mode!=='auto'){updateReadout();return;}if(fps<33){lowStreak++;highStreak=0;}else if(fps>56){highStreak++;lowStreak=0;}else{lowStreak=Math.max(0,lowStreak-1);highStreak=Math.max(0,highStreak-1);}if(lowStreak>=2){const step=fps<24?.16:.10;applyScale(Math.max(.65,currentScale-step));lowStreak=0;}else if(highStreak>=5&&currentScale<userCeiling){applyScale(Math.min(userCeiling,currentScale+.08));highStreak=0;}updateReadout();}
  function setMode(next){mode=['auto','low','balanced','quality'].includes(next)?next:'auto';localStorage.setItem('voxelcraft-performance-profile',mode);const select=document.querySelector('#perfProfile');if(select&&select.value!==mode)select.value=mode;applyMode(true);}
  function applyMode(force=false){const ceiling=mode==='low'?.82:mode==='balanced'?Math.min(1.15,userCeiling):mode==='quality'?userCeiling:initialScale('auto',hardware,userCeiling);applyScale(ceiling,force);if(mode==='low')setRenderDistance(2);else if(mode==='balanced')setRenderDistance(Math.min(3,userRenderDistance));else if(mode==='quality')setRenderDistance(userRenderDistance);else setRenderDistance(hardware.weak?Math.min(3,userRenderDistance):userRenderDistance);applySceneBudget();dispatch();updateReadout();}
  function applyScale(value,force=false){const next=Math.round(clamp(value,.65,userCeiling)*100)/100;if(!force&&Math.abs(next-currentScale)<.04)return;currentScale=next;const now=performance.now();if(!force&&now-lastApply<1200)return;lastApply=now;renderer.setPixelRatio(Math.min(devicePixelRatio||1,currentScale));renderer.setSize(innerWidth,innerHeight,false);dispatch();}
  function applySceneBudget(){if(!scene)return;const budget=visualBudget();scene.traverse((obj)=>{if(!(obj instanceof THREE.Points)||!obj.geometry?.attributes?.position)return;const total=obj.userData.vcOriginalPointCount||obj.geometry.attributes.position.count;obj.userData.vcOriginalPointCount=total;const size=Number(obj.material?.size)||0;if(total>=600&&size<=.12)obj.geometry.setDrawRange(0,Math.max(120,Math.floor(total*budget.weather)));else if(total>=700&&size>.12)obj.geometry.setDrawRange(0,Math.max(260,Math.floor(total*budget.stars)));});dispatch();}
  function visualBudget(){if(mode==='low')return{weather:.38,stars:.55,effects:.55};if(mode==='balanced')return{weather:.68,stars:.78,effects:.78};if(mode==='quality')return{weather:1,stars:1,effects:1};if(currentScale<=.82)return{weather:.42,stars:.58,effects:.58};if(currentScale<=1.05)return{weather:.66,stars:.78,effects:.78};return{weather:.9,stars:.95,effects:.95};}
  function dispatch(){dispatchEvent(new CustomEvent('voxelcraft:performance-profile',{detail:snapshot()}));}
  function snapshot(){const budget=visualBudget();return{mode,scale:currentScale,fps:lastFps,weakHardware:hardware.weak,cores:hardware.cores,memory:hardware.memory,maxTextureSize:hardware.maxTextureSize,renderDistance:currentRenderDistance(),...budget};}
  function currentRenderDistance(){return Number(document.querySelector('#setRender')?.value)||Number(loadJson('voxelcraft-v1-settings',{}).renderDistance)||userRenderDistance;}
  function setRenderDistance(value){const input=document.querySelector('#setRender');if(!input)return;const next=String(clamp(Math.round(value),2,6));if(input.value===next)return;input.value=next;input.dispatchEvent(new Event('change',{bubbles:true}));}
  function installUI(){const panel=document.querySelector('#settingsPanel');if(!panel||panel.querySelector('#perfProfile'))return;const wrap=document.createElement('div');wrap.className='performance-settings';wrap.innerHTML=`<h4>Desempenho</h4><label>Perfil <select id="perfProfile"><option value="auto">Auto</option><option value="low">PC fraco</option><option value="balanced">Equilibrado</option><option value="quality">Qualidade</option></select></label><small id="perfReadout"></small><p style="font-size:12px;opacity:.72">Auto reduz primeiro a resolução interna e partículas. A distância só cai quando o hardware é claramente limitado.</p>`;panel.appendChild(wrap);const select=wrap.querySelector('#perfProfile');select.value=mode;select.addEventListener('change',()=>setMode(select.value));const renderInput=document.querySelector('#setRender'),scaleInput=document.querySelector('#setScale');renderInput?.addEventListener('change',(e)=>{if(e.isTrusted)userRenderDistance=clamp(Number(e.target.value)||userRenderDistance,2,6);});scaleInput?.addEventListener('change',(e)=>{if(!e.isTrusted)return;userCeiling=clamp(Number(e.target.value)||userCeiling,.65,2);if(mode==='quality')applyScale(userCeiling,true);else if(mode==='auto')applyScale(Math.min(currentScale,userCeiling),true);});updateReadout();}
  function updateReadout(){const el=document.querySelector('#perfReadout');if(el)el.textContent=`${lastFps?`${lastFps} FPS · `:''}${currentScale.toFixed(2)}× interno · ${currentRenderDistance()} chunks${hardware.weak?' · hardware modesto detectado':''}`;}
}

function initialScale(mode,hardware,ceiling){if(mode==='low')return Math.min(.82,ceiling);if(mode==='balanced')return Math.min(1.15,ceiling);if(mode==='quality')return ceiling;if(hardware.weak)return Math.min(.95,ceiling);if(hardware.mid)return Math.min(1.2,ceiling);return ceiling;}
function detectHardware(renderer){const cores=Number(navigator.hardwareConcurrency)||4,memory=Number(navigator.deviceMemory)||0,maxTextureSize=Number(renderer.capabilities?.maxTextureSize)||4096,isWebGL2=Boolean(renderer.capabilities?.isWebGL2),weak=(memory>0&&memory<=4)||cores<=4||maxTextureSize<8192||!isWebGL2,mid=!weak&&((memory>0&&memory<=8)||cores<=6);return{cores,memory,maxTextureSize,isWebGL2,weak,mid};}
function loadJson(key,fallback){try{return{...fallback,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return fallback;}}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
