import { ChunkV1 } from './world.js';

export class ChunkWorkerPool{
  constructor(world,{size=2}={}){this.world=world;this.size=Math.max(1,Math.min(4,size));this.workers=[];this.queue=[];this.pending=new Map();this.nextId=1;this.closed=false;this.supported=typeof Worker!=='undefined';if(this.supported){for(let i=0;i<this.size;i++)this.workers.push(this.createWorker(i));}}
  createWorker(index){const worker=new Worker(new URL('./chunk-worker.js',import.meta.url),{type:'module',name:`voxelcraft-chunk-${index}`});const slot={worker,busy:false,index};worker.onmessage=(event)=>this.handle(slot,event.data);worker.onerror=(event)=>{slot.busy=false;console.warn('Chunk worker failed, falling back',event.message);this.supported=false;this.drainFallback();};return slot;}
  request(cx,cz){if(this.closed)return Promise.reject(new Error('ChunkWorkerPool closed'));const key=`${this.world.dimension}:${cx},${cz}`;for(const p of this.pending.values())if(p.key===key)return p.promise;if(this.world.chunks.has(`${cx},${cz}`))return Promise.resolve(this.world.chunks.get(`${cx},${cz}`));let resolve,reject;const promise=new Promise((res,rej)=>{resolve=res;reject=rej}),job={id:this.nextId++,key,cx,cz,seed:this.world.seed,dimension:this.world.dimension,resolve,reject,promise};this.pending.set(job.id,job);this.queue.push(job);this.pump();return promise;}
  pump(){if(this.closed)return;if(!this.supported){this.drainFallback();return;}for(const slot of this.workers){if(slot.busy)continue;const job=this.queue.shift();if(!job)break;slot.busy=true;slot.jobId=job.id;slot.worker.postMessage({id:job.id,seed:job.seed,dimension:job.dimension,cx:job.cx,cz:job.cz});}}
  handle(slot,data){slot.busy=false;slot.jobId=null;const job=this.pending.get(data?.id);if(!job){this.pump();return;}this.pending.delete(job.id);if(!data.ok){job.reject(new Error(data.message||'Chunk worker error'));this.pump();return;}if(job.dimension!==this.world.dimension||job.seed!==this.world.seed){job.resolve(null);this.pump();return;}const chunk=new ChunkV1(data.cx,data.cz,new Uint8Array(data.blocks));this.world.applyEdits(chunk);this.world.chunks.set(`${data.cx},${data.cz}`,chunk);for(const id of data.structures||[])this.world.generatedStructures.add(id);job.resolve(chunk);this.pump();}
  drainFallback(){while(this.queue.length){const job=this.queue.shift();this.pending.delete(job.id);try{if(job.dimension!==this.world.dimension||job.seed!==this.world.seed){job.resolve(null);continue;}const chunk=this.world.generateChunk(job.cx,job.cz);this.world.chunks.set(`${job.cx},${job.cz}`,chunk);job.resolve(chunk);}catch(error){job.reject(error);}}}
  active(){return this.queue.length+[...this.workers].filter((w)=>w.busy).length;}
  close(){this.closed=true;for(const slot of this.workers)slot.worker.terminate();this.workers=[];for(const job of this.pending.values())job.reject(new Error('ChunkWorkerPool closed'));this.pending.clear();this.queue=[];}
}
