import * as THREE from 'three';
import { PointerLockControls } from 'three/addons/controls/PointerLockControls.js';
import { unlockAudio, playBreak, playPlace, playStep, playJump, playLand, playToggleFly, setMasterVolume } from './audio.js';
import { BLOCK, ITEM, BLOCKS, ITEMS, RECIPES, DIMENSIONS, blockDef, itemDef, isLiquid, isSolid } from './v1/catalog.js';
import { InventoryV1, PlayerStatsV1, CraftingSystem, FurnaceSystem, AdvancementSystem, miningSpeed, combatDamage, ItemStack } from './v1/systems.js';
import { WorldV1, CHUNK_SIZE, WORLD_HEIGHT, DEFAULT_RENDER_RADIUS } from './v1/world.js';
import { GameRules, FluxSystem, MinecartSystem, BoatSystem, PortalSystem, explode, igniteTnt, findPortalFrame } from './v1/automation.js';
import { ABLOCK, AITEM, ADVANCED_RECIPES } from './v1/advanced-content.js';
import { EntityManagerV1 } from './v1/entities.js';
import { WorldRendererV1, EntityRendererV1, WeatherRendererV1 } from './v1/renderer.js';
import { SaveDB, AutosaveController } from './v1/save-db.js';
import { CommandConsole } from './v1/commands.js';
import { MultiplayerClient, LocalPresence } from './v1/multiplayer.js';

const $=(s)=>document.querySelector(s);
const canvas=$('#game'),menu=$('#menu'),hud=$('#hud'),hotbar=$('#hotbar'),statsEl=$('#stats'),toast=$('#toast'),statusEl=$('#status');
const inventoryPanel=$('#inventory'),inventoryGrid=$('#inventoryGrid'),playButton=$('#playButton'),newWorldButton=$('#newWorldButton'),saveButton=$('#saveButton'),closeInventoryButton=$('#closeInventory');
const worldNameInput=$('#worldName'),seedInput=$('#seedInput'),gameModeSelect=$('#gameModeSelect'),difficultySelect=$('#difficultySelect'),worldSelect=$('#worldSelect');
const continueButton=$('#continueButton'),exportButton=$('#exportButton'),importButton=$('#importButton'),importFile=$('#importFile'),settingsButton=$('#settingsButton'),settingsPanel=$('#settingsPanel');
const chatBox=$('#chatBox'),chatInput=$('#chatInput'),deathScreen=$('#deathScreen'),respawnButton=$('#respawnButton'),multiplayerPanel=$('#multiplayerPanel');

const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x7eb5e6);scene.fog=new THREE.Fog(0x7eb5e6,48,CHUNK_SIZE*(DEFAULT_RENDER_RADIUS+2.5));
const camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.05,320),controls=new PointerLockControls(camera,canvas);
const hemi=new THREE.HemisphereLight(0xbfe2ff,0x463e2f,1.3),sun=new THREE.DirectionalLight(0xfff0c7,2.25),moon=new THREE.DirectionalLight(0x7c8bc9,.12);scene.add(hemi,sun,moon);
const stars=createStars();scene.add(stars);

let currentWorldId='default',worldName='Novo Mundo',world=new WorldV1(randomSeed(),'overworld');
let inventory=new InventoryV1(),playerStats=new PlayerStatsV1(),crafting=new CraftingSystem(),furnace=new FurnaceSystem(),advancements=new AdvancementSystem(),rules=new GameRules();
let flux=new FluxSystem(world),carts=new MinecartSystem(world),boats=new BoatSystem(world),portal=new PortalSystem(world),entities=createEntityManager(world);
let worldRenderer=new WorldRendererV1(scene,world),entityRenderer=new EntityRendererV1(scene),weatherRenderer=new WeatherRendererV1(scene);
const saveDB=new SaveDB();let autosave=new AutosaveController(saveCurrentWorld,20000);const localPresence=new LocalPresence();
const multiplayer=new MultiplayerClient({onBlock:(m)=>world.setBlock(m.x,m.y,m.z,m.id,{track:true}),onChat:(m)=>appendChat(`<${escapeHtml(m.name)}> ${escapeHtml(m.text)}`),onEvent:(m)=>showToast(m.event?`Multiplayer: ${m.event}`:(m.message||'Evento multiplayer'))});
let commandConsole;

const PLAYER={feet:new THREE.Vector3(.5,40,.5),velocity:new THREE.Vector3(),halfWidth:.3,height:1.8,eyeHeight:1.62,onGround:false,wasGrounded:false,fallDistance:0,stepDistance:0};
commandConsole=createCommandConsole();
const keys=new Set();let jumpQueued=false,inventoryOpen=false,craftingGrid='2x2',activeContainer=null,debugVisible=true,ready=false,paused=true,flying=false,lastFrame=performance.now(),target=null,mining=false,miningKey='',miningProgress=0,attackCooldown=0,damageCooldown=0,lastChunkKey='',fpsFrames=0,fpsTime=0,lastFps=0,portalTransit=false,appSettings=loadSettings(),mountedVehicle=null;
const raycaster=new THREE.Raycaster(),rayDirection=new THREE.Vector3(),rayOrigin=new THREE.Vector3(),forward=new THREE.Vector3(),right=new THREE.Vector3(),wish=new THREE.Vector3(),proposed=new THREE.Vector3();

const outline=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1.006,1.006,1.006)),new THREE.LineBasicMaterial({color:0x111111,transparent:true,opacity:.9}));outline.visible=false;outline.renderOrder=5;scene.add(outline);
const particleGroup=new THREE.Group();scene.add(particleGroup);const particles=[];const particleGeo=new THREE.BoxGeometry(.1,.1,.1);
const survivalHud=ensureHudElement('survivalHud'),xpHud=ensureHudElement('xpHud'),modeBadge=ensureHudElement('modeBadge'),weatherBadge=ensureHudElement('weatherBadge'),bossBar=ensureHudElement('bossBar');
const miningBar=ensureHudElement('miningBar');if(!miningBar.firstElementChild)miningBar.innerHTML='<span></span>';const miningFill=miningBar.firstElementChild;
const damageFlash=document.createElement('div');damageFlash.id='damageFlash';document.body.appendChild(damageFlash);
const minecartViews=new Map(),boatViews=new Map();

applySettings();initialize().catch((e)=>{console.error(e);statusEl.textContent=`Falha ao iniciar: ${e.message}`;});

async function initialize(){await saveDB.open();await saveDB.migrateLegacy();await refreshWorldList();const worlds=await saveDB.listWorlds();if(worlds.length){currentWorldId=worlds[0].id;await loadWorld(currentWorldId);}else await createNewWorld({name:'Primeiro Mundo',seed:randomSeed(),gameMode:'survival',difficulty:'normal'});ready=true;paused=true;renderAllUI();statusEl.textContent=`${worldName} · seed ${world.seed} · ${DIMENSIONS[world.dimension].name}`;window.VoxelCraftV1=publicApi();}

function createEntityManager(w){return new EntityManagerV1(w,{seed:w.seed,onDamagePlayer:(amount,source)=>damagePlayer(amount,source),onDrop:(id,count)=>{inventory.add(id,count);showToast(`+${count} ${itemDef(id)?.name||id}`);renderHotbar();},onExplode:(x,y,z,power)=>{const destroyed=explode(w,x,y,z,power);spawnExplosionParticles(x,y,z,power);if(Math.hypot(PLAYER.feet.x-x,PLAYER.feet.y-y,PLAYER.feet.z-z)<power*2)damagePlayer(Math.max(1,power*3-Math.hypot(PLAYER.feet.x-x,PLAYER.feet.y-y,PLAYER.feet.z-z)),'explosion');for(const d of destroyed)if(multiplayer.connected)multiplayer.sendBlock(d.x,d.y,d.z,0);}});}
function createCommandConsole(){return new CommandConsole({get world(){return world},get stats(){return playerStats},get inventory(){return inventory},get rules(){return rules},get advancements(){return advancements},position:PLAYER.feet,summon:(t,x,y,z)=>entities.spawn(t,x,y,z),changeDimension:(id)=>changeDimension(id),explode:(x,y,z,p)=>explode(world,x,y,z,p),onModeChange:()=>{syncMode();renderInventory();}});}

async function createNewWorld({name='Novo Mundo',seed=randomSeed(),gameMode='survival',difficulty='normal'}={}){ready=false;worldName=String(name||'Novo Mundo').slice(0,48);currentWorldId=await saveDB.uniqueId(worldName);resetSystems(new WorldV1(seed,'overworld'));inventory=new InventoryV1();seedStarterInventory(inventory,gameMode);playerStats=new PlayerStatsV1();playerStats.setGameMode(gameMode);playerStats.difficulty=difficulty;advancements=new AdvancementSystem();rules=new GameRules();crafting=new CraftingSystem();furnace=new FurnaceSystem();spawnPlayer(true);await saveCurrentWorld();await refreshWorldList();ready=true;renderAllUI();statusEl.textContent=`Novo mundo · ${worldName} · seed ${world.seed}`;}
function resetSystems(nextWorld){flux.dispose?.();worldRenderer.dispose?.();entityRenderer?.dispose?.();weatherRenderer?.dispose?.();world=nextWorld;flux=new FluxSystem(world);carts=new MinecartSystem(world);boats=new BoatSystem(world);portal=new PortalSystem(world);entities=createEntityManager(world);worldRenderer=new WorldRendererV1(scene,world,{renderRadius:appSettings.renderDistance});entityRenderer=new EntityRendererV1(scene);weatherRenderer=new WeatherRendererV1(scene);mountedVehicle=null;commandConsole=createCommandConsole();}
function seedStarterInventory(inv,mode){if(mode==='creative'){for(const[id,def]of ITEMS)if(def.kind==='block')inv.add(id,def.maxStack||64);for(const id of[ITEM.DIAMOND_PICKAXE,ITEM.DIAMOND_SWORD,ITEM.BOW,ITEM.ARROW,ITEM.WATER_BUCKET,ITEM.FLINT_STEEL,AITEM.BOAT,AITEM.FISHING_ROD])inv.add(id,id===ITEM.ARROW?64:1);return;}inv.add(ITEM.APPLE,2);}

async function saveCurrentWorld(){if(!ready&&!world)return false;const payload={meta:{name:worldName},world:world.serialize(),automation:{rules:rules.serialize(),carts:carts.serialize(),boats:boats.serialize(),portal:portal.serialize(),entities:entities.serialize(),furnace:furnace.serialize()},player:{position:[PLAYER.feet.x,PLAYER.feet.y,PLAYER.feet.z],rotation:[camera.rotation.x,camera.rotation.y,camera.rotation.z],inventory:inventory.serialize(),stats:playerStats.serialize()},advancements:advancements.serialize()};await saveDB.saveWorld(currentWorldId,payload);return true;}
async function loadWorld(id){const data=await saveDB.loadWorld(id);if(!data)return false;ready=false;currentWorldId=id;worldName=data.meta?.name||id;const w=new WorldV1(data.world.seed||1,data.world.dimension||'overworld');w.load(data.world);resetSystems(w);inventory=new InventoryV1();inventory.load(data.player?.inventory);playerStats=new PlayerStatsV1();playerStats.load(data.player?.stats);rules=new GameRules();rules.load(data.automation?.rules);advancements=new AdvancementSystem();advancements.load(data.advancements);furnace=new FurnaceSystem();furnace.load(data.automation?.furnace);carts.load(data.automation?.carts);boats.load(data.automation?.boats);portal.load(data.automation?.portal);entities.load(data.automation?.entities);if(Array.isArray(data.player?.position))PLAYER.feet.set(...data.player.position);else spawnPlayer(true);if(Array.isArray(data.player?.rotation))camera.rotation.set(...data.player.rotation);camera.position.set(PLAYER.feet.x,PLAYER.feet.y+PLAYER.eyeHeight,PLAYER.feet.z);ready=true;syncMode();renderAllUI();statusEl.textContent=`Carregado · ${worldName} · seed ${world.seed}`;return true;}
async function refreshWorldList(){if(!worldSelect)return;const list=await saveDB.listWorlds();worldSelect.innerHTML='';for(const w of list){const opt=document.createElement('option');opt.value=w.id;opt.textContent=`${w.name} · ${w.gameMode} · ${new Date(w.updatedAt).toLocaleDateString()}`;worldSelect.appendChild(opt);}if(list.some((w)=>w.id===currentWorldId))worldSelect.value=currentWorldId;}

function spawnPlayer(resetRotation=false){let x=.5,z=.5,y=world.surfaceY(x,z);let attempts=0;while(y<3&&attempts++<64){x=(Math.random()-.5)*40;z=(Math.random()-.5)*40;y=world.surfaceY(x,z);}PLAYER.feet.set(x,y+.05,z);PLAYER.velocity.set(0,0,0);PLAYER.onGround=false;PLAYER.fallDistance=0;if(resetRotation)camera.rotation.set(0,0,0);camera.position.set(PLAYER.feet.x,PLAYER.feet.y+PLAYER.eyeHeight,PLAYER.feet.z);playerStats.spawn={dimension:world.dimension,x:PLAYER.feet.x,y:PLAYER.feet.y,z:PLAYER.feet.z};}
function respawn(){if(playerStats.gameMode==='hardcore'){showToast('Hardcore: este mundo terminou.');return;}playerStats.resetAfterDeath();if(playerStats.spawn.dimension!==world.dimension)changeDimension(playerStats.spawn.dimension,{position:playerStats.spawn});else PLAYER.feet.set(playerStats.spawn.x,playerStats.spawn.y,playerStats.spawn.z);PLAYER.velocity.set(0,0,0);deathScreen?.classList.remove('visible');camera.position.set(PLAYER.feet.x,PLAYER.feet.y+PLAYER.eyeHeight,PLAYER.feet.z);controls.lock();}

function updatePlayer(dt){if(!controls.isLocked||!ready||playerStats.dead)return;if(updateMountedVehicle(dt))return;PLAYER.wasGrounded=PLAYER.onGround;camera.getWorldDirection(forward);forward.y=0;if(forward.lengthSq()<.001)forward.set(0,0,-1);forward.normalize();right.set(-forward.z,0,forward.x);wish.set(0,0,0);if(keys.has('KeyW'))wish.add(forward);if(keys.has('KeyS'))wish.sub(forward);if(keys.has('KeyD'))wish.add(right);if(keys.has('KeyA'))wish.sub(right);if(wish.lengthSq()>1)wish.normalize();
  const underwater=isUnderwater(),sprinting=(keys.has('ShiftLeft')||keys.has('ShiftRight'))&&playerStats.hunger>6,creative=playerStats.gameMode==='creative',base=underwater?2.7:sprinting?6.5:4.35,speed=base*playerStats.effects.multiplier('speed'),canFly=creative&&flying,accel=canFly?13:PLAYER.onGround?18:underwater?7:5.3,blend=Math.min(1,accel*dt);PLAYER.velocity.x=THREE.MathUtils.lerp(PLAYER.velocity.x,wish.x*speed,blend);PLAYER.velocity.z=THREE.MathUtils.lerp(PLAYER.velocity.z,wish.z*speed,blend);
  if(canFly){const vertical=(keys.has('Space')?1:0)-(keys.has('ControlLeft')||keys.has('ControlRight')?1:0);PLAYER.velocity.y=THREE.MathUtils.lerp(PLAYER.velocity.y,vertical*(sprinting?10:7),Math.min(1,12*dt));PLAYER.onGround=false;}else if(underwater){PLAYER.velocity.y+=((keys.has('Space')?5.2:-1)-PLAYER.velocity.y)*Math.min(1,3*dt);}else{if(jumpQueued&&PLAYER.onGround){PLAYER.velocity.y=7.3;PLAYER.onGround=false;playJump();playerStats.addExhaustion(.05);}PLAYER.velocity.y=Math.max(-34,PLAYER.velocity.y-(DIMENSIONS[world.dimension]?.gravity||20.5)*dt);}jumpQueued=false;
  const travel=Math.max(Math.abs(PLAYER.velocity.x*dt),Math.abs(PLAYER.velocity.y*dt),Math.abs(PLAYER.velocity.z*dt)),steps=Math.max(1,Math.ceil(travel/.15)),stepDt=dt/steps;for(let i=0;i<steps;i++){if(!canFly)PLAYER.onGround=false;moveAxis('x',PLAYER.velocity.x*stepDt);moveAxis('z',PLAYER.velocity.z*stepDt);const oldVy=PLAYER.velocity.y;proposed.copy(PLAYER.feet);proposed.y+=oldVy*stepDt;if(!collidesAt(proposed)){PLAYER.feet.y=proposed.y;if(oldVy<0&&!canFly&&!underwater)PLAYER.fallDistance+=-oldVy*stepDt;}else{if(oldVy<0&&!canFly){PLAYER.onGround=true;if(PLAYER.fallDistance>3.2)damagePlayer(Math.floor(PLAYER.fallDistance-3),'fall');PLAYER.fallDistance=0;}PLAYER.velocity.y=0;}}
  if(!canFly&&!underwater){const probe=PLAYER.feet.clone();probe.y-=.04;if(collidesAt(probe))PLAYER.onGround=true;}if(!PLAYER.wasGrounded&&PLAYER.onGround)playLand();
  if(PLAYER.onGround&&wish.lengthSq()>.1){const dist=Math.hypot(PLAYER.velocity.x,PLAYER.velocity.z)*dt;PLAYER.stepDistance+=dist;if(sprinting)playerStats.addExhaustion(dist*.015);if(PLAYER.stepDistance>2.1){PLAYER.stepDistance=0;const floorId=world.getBlock(Math.floor(PLAYER.feet.x),Math.floor(PLAYER.feet.y-.08),Math.floor(PLAYER.feet.z));playStep(blockDef(floorId)?.material||'stone');}}
  camera.position.set(PLAYER.feet.x,PLAYER.feet.y+PLAYER.eyeHeight,PLAYER.feet.z);const targetFov=appSettings.fov+(sprinting&&wish.lengthSq()>.1?5:underwater?-3:0);camera.fov=THREE.MathUtils.lerp(camera.fov,targetFov,Math.min(1,dt*8));camera.updateProjectionMatrix();checkHazards(dt);checkPortal();
}
function updateMountedVehicle(dt){if(!mountedVehicle)return false;const list=mountedVehicle.type==='boat'?boats.boats:carts.carts,vehicle=list.find((v)=>v.id===mountedVehicle.id);if(!vehicle){mountedVehicle=null;return false;}camera.getWorldDirection(forward);forward.y=0;if(forward.lengthSq()<.001)forward.set(0,0,-1);forward.normalize();const drive=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),turn=(keys.has('KeyA')?1:0)-(keys.has('KeyD')?1:0);if(mountedVehicle.type==='boat')boats.steer(vehicle,drive,turn,dt);else if(drive){vehicle.vx+=forward.x*drive*dt*4;vehicle.vz+=forward.z*drive*dt*4;}vehicle.passenger='player';PLAYER.feet.set(vehicle.x,vehicle.y+.35,vehicle.z);PLAYER.velocity.set(0,0,0);camera.position.set(PLAYER.feet.x,PLAYER.feet.y+PLAYER.eyeHeight,PLAYER.feet.z);return true;}
function toggleVehicleMount(){if(mountedVehicle){const list=mountedVehicle.type==='boat'?boats.boats:carts.carts,vehicle=list.find((v)=>v.id===mountedVehicle.id);if(vehicle)vehicle.passenger=null;mountedVehicle=null;showToast('Você desmontou.');return;}let best=null;for(const[type,list]of[['boat',boats.boats],['cart',carts.carts]])for(const v of list){const d=Math.hypot(v.x-PLAYER.feet.x,v.y-PLAYER.feet.y,v.z-PLAYER.feet.z);if(d<2.4&&(!best||d<best.d))best={type,id:v.id,d};}if(best){mountedVehicle={type:best.type,id:best.id};showToast(best.type==='boat'?'Barco montado.':'Carrinho montado.');}else showToast('Nenhum veículo próximo.');}
function moveAxis(axis,amount){proposed.copy(PLAYER.feet);proposed[axis]+=amount;if(!collidesAt(proposed))PLAYER.feet[axis]=proposed[axis];else PLAYER.velocity[axis]=0;}
function collidesAt(p){const minX=Math.floor(p.x-PLAYER.halfWidth+.001),maxX=Math.floor(p.x+PLAYER.halfWidth-.001),minY=Math.floor(p.y+.001),maxY=Math.floor(p.y+PLAYER.height-.001),minZ=Math.floor(p.z-PLAYER.halfWidth+.001),maxZ=Math.floor(p.z+PLAYER.halfWidth-.001);if(minY<0)return true;for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++)for(let z=minZ;z<=maxZ;z++)if(isSolid(world.getBlock(x,y,z)))return true;return false;}
function blockIntersectsPlayer(x,y,z){return x+1>PLAYER.feet.x-PLAYER.halfWidth&&x<PLAYER.feet.x+PLAYER.halfWidth&&y+1>PLAYER.feet.y&&y<PLAYER.feet.y+PLAYER.height&&z+1>PLAYER.feet.z-PLAYER.halfWidth&&z<PLAYER.feet.z+PLAYER.halfWidth;}
function isUnderwater(){return world.getBlock(Math.floor(camera.position.x),Math.floor(camera.position.y),Math.floor(camera.position.z))===BLOCK.WATER;}
function checkHazards(dt){const fx=Math.floor(PLAYER.feet.x),fy=Math.floor(PLAYER.feet.y),fz=Math.floor(PLAYER.feet.z),feet=world.getBlock(fx,fy,fz),body=world.getBlock(fx,fy+1,fz);if(feet===BLOCK.LAVA||body===BLOCK.LAVA){playerStats.ignite(5);damageCooldown-=dt;if(damageCooldown<=0){damageCooldown=.55;damagePlayer(4,'lava');}}else if(feet===BLOCK.CACTUS||body===BLOCK.CACTUS){damageCooldown-=dt;if(damageCooldown<=0){damageCooldown=.7;damagePlayer(1,'cactus');}}else damageCooldown=Math.max(0,damageCooldown-dt);}

function updateTarget(){if(!controls.isLocked){target=null;outline.visible=false;cancelMining();return;}camera.getWorldDirection(rayDirection);target=voxelRaycast(world,camera.position,rayDirection,6);if(target){outline.visible=true;outline.position.set(target.remove[0]+.5,target.remove[1]+.5,target.remove[2]+.5);if(mining&&miningKey!==target.remove.join(','))cancelMining();}else{outline.visible=false;cancelMining();}}
function voxelRaycast(w,origin,dir,maxDist){const step=.045,last=[Math.floor(origin.x),Math.floor(origin.y),Math.floor(origin.z)];for(let d=0;d<=maxDist;d+=step){const x=Math.floor(origin.x+dir.x*d),y=Math.floor(origin.y+dir.y*d),z=Math.floor(origin.z+dir.z*d),id=w.getBlock(x,y,z);if(id!==BLOCK.AIR&&!isLiquid(id)&&id!==BLOCK.PORTAL)return{remove:[x,y,z],place:[...last],id,distance:d};last[0]=x;last[1]=y;last[2]=z;}return null;}
function liquidRaycast(fluid=BLOCK.WATER,maxDist=6){camera.getWorldDirection(rayDirection);for(let d=0;d<=maxDist;d+=.08){const x=Math.floor(camera.position.x+rayDirection.x*d),y=Math.floor(camera.position.y+rayDirection.y*d),z=Math.floor(camera.position.z+rayDirection.z*d);if(world.getBlock(x,y,z)===fluid)return{x,y,z};}return null;}
function findMobTarget(){camera.getWorldDirection(rayDirection);let best=null,bestScore=Infinity;for(const e of entities.entities){if(e.dead)continue;const vx=e.x-camera.position.x,vy=e.y+1-camera.position.y,vz=e.z-camera.position.z,forwardDist=vx*rayDirection.x+vy*rayDirection.y+vz*rayDirection.z;if(forwardDist<0||forwardDist>4.5)continue;const len2=vx*vx+vy*vy+vz*vz,perp=Math.sqrt(Math.max(0,len2-forwardDist*forwardDist));if(perp<.75&&perp<bestScore){best=e;bestScore=perp;}}return best;}

function startPrimary(){if(attackCooldown>0)return;const mob=findMobTarget();if(mob){attackMob(mob);return;}if(!target)return;if(playerStats.gameMode==='creative'){breakTarget(true);return;}const def=blockDef(target.id);if(!def||!Number.isFinite(def.hardness)){showToast('Este bloco não pode ser quebrado.');return;}mining=true;miningKey=target.remove.join(',');miningProgress=0;miningBar.classList.add('active');}
function updateMining(dt){if(!mining||!target||target.remove.join(',')!==miningKey)return;const def=blockDef(target.id),stack=inventory.selectedStack(),profile=miningSpeed(def,stack,playerStats.effects),eff=Number(stack?.data?.enchantments?.efficiency)||0,speed=profile.speed*(1+eff*.18);miningProgress+=dt*speed/Math.max(.05,def.hardness);miningFill.style.transform=`scaleX(${Math.min(1,miningProgress)})`;if(miningProgress>=1)breakTarget(profile.harvest);}
function cancelMining(){mining=false;miningKey='';miningProgress=0;miningFill.style.transform='scaleX(0)';miningBar.classList.remove('active');}
function breakTarget(harvest){if(!target)return;const[x,y,z]=target.remove,id=world.getBlock(x,y,z),def=blockDef(id);if(id===BLOCK.BEDROCK)return;world.setBlock(x,y,z,BLOCK.AIR);if(multiplayer.connected)multiplayer.sendBlock(x,y,z,0);spawnBreakParticles(x,y,z,def?.color||0x999999);playBreak(def?.tool==='axe'?'wood':def?.liquid?'sand':'stone');if(playerStats.gameMode!=='creative'){if(harvest){const drop=blockDropV1(id,world.getState(x,y,z));if(drop)inventory.add(drop[0],drop[1]);if([BLOCK.COAL_ORE,BLOCK.IRON_ORE,BLOCK.GOLD_ORE,BLOCK.DIAMOND_ORE].includes(id))playerStats.addXp(id===BLOCK.DIAMOND_ORE?5:id===BLOCK.GOLD_ORE?3:2);}if(itemDef(inventory.selectedStack()?.id)?.kind==='tool')inventory.damageSelected(1);playerStats.addExhaustion(.02);}cancelMining();target=null;renderHotbar();}
function blockDropV1(id,state){if(id===BLOCK.GRASS)return[ITEM.DIRT,1];if(id===BLOCK.STONE)return[ITEM.COBBLE,1];if(id===BLOCK.COAL_ORE)return[ITEM.COAL,1];if(id===BLOCK.IRON_ORE)return[ITEM.IRON_ORE,1];if(id===BLOCK.GOLD_ORE)return[ITEM.GOLD_ORE,1];if(id===BLOCK.DIAMOND_ORE)return[ITEM.DIAMOND,1];if(id===BLOCK.CROP)return state?.age>=7?[ITEM.WHEAT,1+Math.floor(Math.random()*2)]:[ITEM.SEEDS,1];if(id===BLOCK.LEAVES)return Math.random()<.08?[ITEM.APPLE,1]:null;return ITEMS.has(id)?[id,1]:null;}

function secondaryAction(){if(!controls.isLocked)return;if(target&&interactTargetBlock())return;const stack=inventory.selectedStack(),def=itemDef(stack?.id);if(!stack||!def)return;if(def.kind==='food'){if(playerStats.eat(def)){inventory.consumeSelected(1);showToast(`Comeu ${def.name}`);renderHotbar();}return;}if(def.kind==='potion'){usePotion(stack,def);return;}if(def.tool==='bucket'){useBucket(stack,def);return;}if(def.vehicle==='boat'){placeBoat();return;}if(def.kind==='block')placeSelectedBlock(stack,def);}
function interactTargetBlock(){const[x,y,z]=target.remove,id=world.getBlock(x,y,z),stack=inventory.selectedStack(),def=itemDef(stack?.id);if(id===BLOCK.LEVER){const on=flux.toggleLever(x,y,z);showToast(on?'Flux ligado':'Flux desligado');return true;}if(id===ABLOCK.REPEATER){const s=world.getState(x,y,z)||{facing:[1,0,0],delay:.2,on:false},delays:[.1,.2,.4,.8],next=delays[(delays.indexOf(s.delay)+1)%delays.length];world.setState(x,y,z,{...s,delay:next});showToast(`Atraso ${next.toFixed(1)}s`);return true;}if(id===BLOCK.CRAFTING_TABLE){openInventory('3x3',{type:'crafting',x,y,z});return true;}if(id===BLOCK.FURNACE){openInventory('3x3',{type:'furnace',x,y,z});return true;}if(id===BLOCK.CHEST||id===ABLOCK.HOPPER||id===ABLOCK.DISPENSER){openInventory('3x3',{type:'chest',x,y,z});return true;}if(id===BLOCK.BED){playerStats.spawn={dimension:world.dimension,x:x+.5,y:y+1,z:z+.5};if(world.dimension==='overworld'&&(world.time>.62||world.time<.12))world.time=.24;showToast('Ponto de renascimento definido.');return true;}if(id===BLOCK.TNT&&def?.tool==='igniter'){igniteTnt(world,x,y,z,1.6,()=>{});inventory.damageSelected(1);return true;}if(id===BLOCK.OBSIDIAN&&def?.tool==='igniter'){const axis=findPortalNear(x,y,z);if(axis){portal.createPortal(x,y+1,z);inventory.damageSelected(1);showToast('Portal ativado.');return true;}}
  if(stack?.id===ITEM.SEEDS&&[BLOCK.DIRT,BLOCK.GRASS,BLOCK.FARMLAND].includes(id)){if(id!==BLOCK.FARMLAND)world.setBlock(x,y,z,BLOCK.FARMLAND,{state:{hydrated:world.findNearbyFluid(x,y,z,BLOCK.WATER,4)}});if(world.getBlock(x,y+1,z)===BLOCK.AIR){world.setBlock(x,y+1,z,BLOCK.CROP,{state:{age:0}});inventory.consumeSelected(1);showToast('Sementes plantadas.');renderHotbar();return true;}}
  if(stack?.id===ITEM.MINECART&&[BLOCK.RAIL,ABLOCK.POWERED_RAIL].includes(id)){const cart=carts.spawn(x+.5,y+.45,z+.5);if(cart){if(playerStats.gameMode!=='creative')inventory.consumeSelected(1);showToast('Carrinho colocado. Pressione R perto dele para montar.');return true;}}
  return false;}
function findPortalNear(x,y,z){for(let ox=-2;ox<=2;ox++)for(let oy=-4;oy<=0;oy++)for(let oz=-2;oz<=2;oz++){const axis=findPortalFrame(world,x+ox,y+oy,z+oz);if(axis)return axis;}return null;}
function placeSelectedBlock(stack,def){if(!target)return;const[x,y,z]=target.place,id=def.block;if(world.getBlock(x,y,z)!==BLOCK.AIR&&blockDef(world.getBlock(x,y,z))?.replaceable!==true)return;if(isSolid(id)&&blockIntersectsPlayer(x,y,z)){showToast('Você ocupa esse espaço.');return;}let state=null;if([BLOCK.PISTON,ABLOCK.STICKY_PISTON,ABLOCK.REPEATER,ABLOCK.COMPARATOR,ABLOCK.DISPENSER,ABLOCK.OBSERVER].includes(id)){camera.getWorldDirection(rayDirection);const facing=Math.abs(rayDirection.x)>Math.abs(rayDirection.z)?[-Math.sign(rayDirection.x),0,0]:[0,0,-Math.sign(rayDirection.z)];state={facing,extended:false};if(id===ABLOCK.REPEATER)state={facing,delay:.2,on:false};}if(id===ABLOCK.HOPPER)state={facing:[0,-1,0]};if(id===ABLOCK.POWERED_RAIL)state={powered:false};if(id===BLOCK.CROP)state={age:0};if(isLiquid(id))state={level:0,source:true};world.setBlock(x,y,z,id,{state});if(multiplayer.connected)multiplayer.sendBlock(x,y,z,id);if(playerStats.gameMode!=='creative')inventory.consumeSelected(1);playPlace(blockDef(id)?.tool==='axe'?'wood':'stone');renderHotbar();}
function placeBoat(){const p=liquidRaycast(BLOCK.WATER,6);if(!p){showToast('Aponte para a água.');return;}const boat=boats.spawn(p.x+.5,p.y+.3,p.z+.5);if(!boat)return;if(playerStats.gameMode!=='creative')inventory.consumeSelected(1);showToast('Barco colocado. Pressione R perto dele para montar.');renderHotbar();}
function useBucket(stack,def){if(def.fluid){if(!target)return;const[x,y,z]=target.place;world.setBlock(x,y,z,def.fluid,{state:{level:0,source:true}});if(playerStats.gameMode!=='creative'){inventory.consumeSelected(1);inventory.add(ITEM.BUCKET,1);}renderHotbar();return;}if(!target)return;const[x,y,z]=target.remove,id=world.getBlock(x,y,z);if(id===BLOCK.WATER||id===BLOCK.LAVA){world.setBlock(x,y,z,BLOCK.AIR);if(playerStats.gameMode!=='creative'){inventory.consumeSelected(1);inventory.add(id===BLOCK.WATER?ITEM.WATER_BUCKET:ITEM.LAVA_BUCKET,1);}renderHotbar();}}
function usePotion(stack,def){if(def.effect==='instant_health')playerStats.heal(8*(def.amplifier||1));else playerStats.effects.add(def.effect,def.duration||60,def.amplifier||0);inventory.consumeSelected(1);showToast(`Usou ${def.name}`);renderHotbar();}
function attackMob(mob){attackCooldown=.45;const stack=inventory.selectedStack(),damage=combatDamage(stack,playerStats.effects),result=entities.attack(mob,damage,PLAYER.feet);if(itemDef(stack?.id)?.kind==='tool')inventory.damageSelected(1);playerStats.addExhaustion(.1);if(result?.killed)playerStats.addXp(mob.kind==='boss'?80:mob.kind==='hostile'||mob.kind==='ranged'?5:2);renderHotbar();}
function damagePlayer(amount,source){if(damageCooldown>0&&source!=='fall')return 0;const dealt=playerStats.damage(amount,inventory,source);if(dealt>0){damageCooldown=.45;damageFlash.classList.remove('hit');void damageFlash.offsetWidth;damageFlash.classList.add('hit');showToast(`-${dealt.toFixed(1)} ❤ ${source}`);renderSurvivalHud();if(playerStats.dead)handleDeath();}return dealt;}
function handleDeath(){controls.unlock();paused=true;deathScreen?.classList.add('visible');if(playerStats.gameMode==='hardcore')deathScreen?.classList.add('hardcore');saveCurrentWorld();}

function openInventory(grid='2x2',container=null){if(!controls.isLocked&&!inventoryOpen)return;inventoryOpen=true;craftingGrid=grid;activeContainer=container;controls.unlock();menu.classList.remove('visible');inventoryPanel.classList.add('visible');renderInventory();}
function closeInventory(){inventoryOpen=false;activeContainer=null;inventoryPanel.classList.remove('visible');menu.classList.add('visible');}
function renderInventory(){if(!inventoryGrid)return;inventoryGrid.innerHTML='';const itemsSection=document.createElement('section');itemsSection.className='inventory-section';itemsSection.innerHTML='<h3>Inventário</h3>';const list=document.createElement('div');list.className='item-list';inventory.slots.forEach((stack,index)=>{if(!stack)return;const def=itemDef(stack.id),b=document.createElement('button');b.className='inv-item';b.innerHTML=`${itemIcon(stack.id)}<strong>${escapeHtml(def?.name||String(stack.id))}</strong><small>${stack.count}${stack.data.durability!=null?` · ${stack.data.durability} dur`:''}</small>`;b.addEventListener('click',()=>{if(def?.kind==='armor'){inventory.equipFromSlot(index);renderInventory();renderSurvivalHud();return;}const hotIndex=inventory.hotbar.indexOf(index);if(hotIndex>=0)inventory.setSelected(hotIndex);else inventory.hotbar[inventory.selected]=index;renderHotbar();});list.appendChild(b);});itemsSection.appendChild(list);inventoryGrid.appendChild(itemsSection);
  const craftSection=document.createElement('section');craftSection.className='inventory-section';craftSection.innerHTML=`<h3>Crafting ${craftingGrid}</h3>`;const recipes=document.createElement('div');recipes.className='recipe-list';for(const r of [...RECIPES,...ADVANCED_RECIPES].filter((r)=>r.grid==='any'||r.grid===craftingGrid||craftingGrid==='3x3')){const b=document.createElement('button');b.className='recipe';const available=r.in.every(([id,n])=>inventory.has(id,n));b.disabled=!available;b.innerHTML=`<strong>${escapeHtml(itemDef(r.out[0])?.name||r.id)} ×${r.out[1]}</strong><small>${r.in.map(([id,n])=>`${n} ${itemDef(id)?.name||id}`).join(' + ')}</small>`;b.addEventListener('click',()=>{if(crafting.craft(inventory,r.id,craftingGrid)){showToast('Item criado.');renderInventory();renderHotbar();}});recipes.appendChild(b);}craftSection.appendChild(recipes);inventoryGrid.appendChild(craftSection);
  renderArmorSection();if(activeContainer?.type==='furnace')renderFurnaceSection();if(activeContainer?.type==='chest')renderChestSection();renderEnchantSection();if(playerStats.gameMode==='creative')renderCreativeSection();}
function renderArmorSection(){const section=document.createElement('section');section.className='inventory-section';section.innerHTML='<h3>Armadura</h3>';for(const slot of['head','chest','legs','feet']){const s=inventory.armor[slot],p=document.createElement('p');p.textContent=`${slot}: ${s?itemDef(s.id)?.name:'vazio'}`;section.appendChild(p);}inventoryGrid.appendChild(section);}
function renderFurnaceSection(){const s=document.createElement('section');s.className='inventory-section';s.innerHTML=`<h3>Fornalha</h3><p>Combustível: ${furnace.fuel.toFixed(0)}s · progresso ${furnace.progress.toFixed(1)}s</p>`;const fuel=document.createElement('button');fuel.textContent='Adicionar carvão';fuel.disabled=!inventory.has(ITEM.COAL);fuel.onclick=()=>{furnace.loadFuel(inventory);renderInventory();renderHotbar();};s.appendChild(fuel);for(const id of[ITEM.IRON_ORE,ITEM.GOLD_ORE,ITEM.RAW_PORK,ITEM.RAW_BEEF,ITEM.RAW_CHICKEN,ITEM.FISH])if(inventory.has(id)){const b=document.createElement('button');b.textContent=`Assar ${itemDef(id)?.name}`;b.disabled=Boolean(furnace.input);b.onclick=()=>{furnace.setInput(inventory,id);renderInventory();};s.appendChild(b);}if(furnace.output){const take=document.createElement('button');take.textContent=`Pegar ${itemDef(furnace.output.id)?.name}`;take.onclick=()=>{furnace.takeOutput(inventory);renderInventory();renderHotbar();};s.appendChild(take);}inventoryGrid.appendChild(s);}
function chestKey(){return activeContainer?`${activeContainer.x},${activeContainer.y},${activeContainer.z}`:null;}
function getChestInventory(){const key=chestKey();if(!key)return null;let raw=world.blockEntities.get(key);const chest=new InventoryV1(activeContainer&&world.getBlock(activeContainer.x,activeContainer.y,activeContainer.z)===ABLOCK.HOPPER?5:27);if(raw?.inventory)chest.load(raw.inventory);else if(Array.isArray(raw?.slots))chest.slots=raw.slots.map((s)=>ItemStack.from(s));return chest;}
function saveChest(chest){const key=chestKey();if(key)world.blockEntities.set(key,{type:'chest',inventory:chest.serialize()});}
function renderChestSection(){const chest=getChestInventory(),s=document.createElement('section');s.className='inventory-section';s.innerHTML='<h3>Container</h3>';chest.slots.forEach((stack,index)=>{if(!stack)return;const b=document.createElement('button');b.textContent=`${itemDef(stack.id)?.name} ×${stack.count}`;b.onclick=()=>{if(inventory.add(stack.id,stack.count,stack.data)){chest.slots[index]=null;saveChest(chest);renderInventory();renderHotbar();}};s.appendChild(b);});const store=document.createElement('button');store.textContent='Guardar item selecionado';store.onclick=()=>{const stack=inventory.selectedStack();if(stack&&chest.add(stack.id,stack.count,stack.data)){inventory.slots[inventory.hotbar[inventory.selected]]=null;saveChest(chest);renderInventory();renderHotbar();}};s.appendChild(store);inventoryGrid.appendChild(s);}
function renderEnchantSection(){const stack=inventory.selectedStack(),def=itemDef(stack?.id);if(!stack||!['tool','armor'].includes(def?.kind))return;const s=document.createElement('section');s.className='inventory-section';s.innerHTML=`<h3>Encantamento</h3><p>Nível ${playerStats.level}</p>`;const b=document.createElement('button');b.textContent='Encantar (3 níveis)';b.disabled=playerStats.level<3;b.onclick=()=>{if(playerStats.level<3)return;playerStats.level-=3;stack.data.enchantments=stack.data.enchantments||{};const key=def.tool==='sword'?'sharpness':def.tool==='pickaxe'?'efficiency':'protection';stack.data.enchantments[key]=Math.min(5,(stack.data.enchantments[key]||0)+1);showToast(`${key} ${stack.data.enchantments[key]}`);renderInventory();renderHotbar();};s.appendChild(b);inventoryGrid.appendChild(s);}
function renderCreativeSection(){const s=document.createElement('section');s.className='inventory-section creative-catalog';s.innerHTML='<h3>Catálogo Creative</h3>';for(const[id,def]of ITEMS){const b=document.createElement('button');b.className='creative-item';b.textContent=def.name;b.onclick=()=>{inventory.add(id,def.maxStack===1?1:64);renderInventory();renderHotbar();};s.appendChild(b);}inventoryGrid.appendChild(s);}

function renderHotbar(){hotbar.innerHTML='';for(let i=0;i<9;i++){const slotIndex=inventory.hotbar[i],stack=inventory.slots[slotIndex],def=itemDef(stack?.id),b=document.createElement('div');b.className=`slot${i===inventory.selected?' selected':''}${stack?'':' empty'}`;b.innerHTML=`<span class="num">${i+1}</span>${stack?itemIcon(stack.id):''}<span class="label">${escapeHtml(def?.name||'')}</span>${stack?.count>1?`<span class="count">${stack.count}</span>`:''}${stack?.data?.durability!=null?`<span class="durability">${stack.data.durability}</span>`:''}`;hotbar.appendChild(b);}}
function renderSurvivalHud(){const hearts=Math.ceil(playerStats.health/2),food=Math.ceil(playerStats.hunger/2),air=Math.ceil(playerStats.air/2),armor=Math.ceil(inventory.armorPoints()/2);survivalHud.innerHTML=`<span class="hearts">${'♥'.repeat(hearts)}${'♡'.repeat(10-hearts)}</span><span class="armor">${armor?`◆`.repeat(Math.min(10,armor)):''}</span><span class="hunger">${'◆'.repeat(food)}${'◇'.repeat(10-food)}</span>${air<10?`<span class="air">${'●'.repeat(air)}${'○'.repeat(10-air)}</span>`:''}`;xpHud.innerHTML=`Lv ${playerStats.level} · XP ${playerStats.xp.toFixed(1)}/${playerStats.xpForNext()}`;}
function renderAllUI(){renderHotbar();renderSurvivalHud();syncMode();if(inventoryOpen)renderInventory();}
function syncMode(){flying=playerStats.gameMode==='creative'&&flying;modeBadge.textContent=`${playerStats.gameMode.toUpperCase()}${flying?' · VOO':''}${mountedVehicle?` · ${mountedVehicle.type==='boat'?'BARCO':'CARRINHO'}`:''}`;modeBadge.classList.toggle('creative',playerStats.gameMode==='creative');}
function itemIcon(id){const def=itemDef(id);if(def?.kind==='block'){const c=`#${(blockDef(id)?.color||0xffffff).toString(16).padStart(6,'0')}`;return`<span class="swatch" style="background:${c}"></span>`;}const icons={tool:'⚒',armor:'⛨',food:'●',potion:'⚗',material:'◆',ammo:'➶',vehicle:'▣'};return`<span class="item-icon">${icons[def?.kind]||'▪'}</span>`;}

function updateSky(dt){if(rules.get('doDaylightCycle'))world.tick(dt);else{const old=world.time;world.tick(dt);world.time=old;}if(!rules.get('doWeatherCycle')){world.weather.type='clear';world.weather.target=0;}const angle=world.time*Math.PI*2,sunY=Math.sin(angle),day=world.dimension==='overworld'?THREE.MathUtils.smoothstep(sunY,-.15,.34):world.dimension==='emberdeep'?.18:.28;sun.position.set(Math.cos(angle)*55,sunY*55,22);moon.position.copy(sun.position).multiplyScalar(-1);sun.intensity=world.dimension==='overworld'?day*2.3:.2;moon.intensity=world.dimension==='overworld'?(1-day)*.25:.08;hemi.intensity=world.dimension==='overworld'?.18+day*1.22:world.dimension==='emberdeep'?.35:.45;const sky=world.dimension==='overworld'?new THREE.Color(0x09111f).lerp(new THREE.Color(0x7eb5e6),day):new THREE.Color(DIMENSIONS[world.dimension].sky);if(world.weather.type==='storm')sky.multiplyScalar(.65);scene.background.copy(sky);scene.fog.color.copy(sky);stars.visible=world.dimension!=='overworld'||day<.42;weatherBadge.textContent=world.dimension==='overworld'?(world.weather.type==='clear'?'☀':world.weather.type==='rain'?'☂ Chuva':'ϟ Tempestade'):DIMENSIONS[world.dimension].name;}
function daylight(){if(world.dimension!=='overworld')return world.dimension==='emberdeep'?.2:.3;return THREE.MathUtils.smoothstep(Math.sin(world.time*Math.PI*2),-.15,.34);}

function updateSimulation(dt){if(paused||!ready)return;attackCooldown=Math.max(0,attackCooldown-dt);portal.tick(dt);flux.tick(dt);carts.tick(dt);boats.tick(dt);furnace.tick(dt,playerStats);playerStats.tick(dt,{underwater:isUnderwater(),inventory});if(!rules.get('naturalRegeneration'))playerStats.regenTimer=0;entities.tick(dt,PLAYER.feet,{daylight:daylight(),difficulty:playerStats.difficulty,doMobSpawning:rules.get('doMobSpawning')});advancements.update({items:{has:(id)=>inventory.has(id)},dimension:world.dimension,flags:entities.flags});for(const a of advancements.popNotifications())showToast(`🏆 ${a.title}`);autosave.tick(dt);if(playerStats.dead&&!deathScreen?.classList.contains('visible'))handleDeath();if(world.dimension==='voidlands'&&!entities.flags.bossDefeated&&!entities.entities.some((e)=>e.type==='void_titan')&&Math.hypot(PLAYER.feet.x,PLAYER.feet.z)>18)entities.spawnBoss(PLAYER.feet.x+14,world.surfaceY(PLAYER.feet.x+14,PLAYER.feet.z),PLAYER.feet.z);}
function updateRender(dt){worldRenderer.update(PLAYER.feet.x,PLAYER.feet.z);entityRenderer.update(entities,multiplayer.interpolatedPlayers());weatherRenderer.update(dt,camera,world.weather,world.biomeAt(PLAYER.feet.x,PLAYER.feet.z));updateParticles(dt);updateVehicleViews();updateBossBar();renderer.render(scene,camera);}
function updateBossBar(){const boss=entities.entities.find((e)=>e.kind==='boss'&&!e.dead);bossBar.classList.toggle('visible',Boolean(boss));if(boss)bossBar.innerHTML=`<strong>${escapeHtml(blockDef(BLOCK.VOIDSTONE)?.name?'Titã do Vazio':'Boss')}</strong><span><i style="width:${(boss.health/boss.maxHealth*100).toFixed(1)}%"></i></span>`;}
function updateVehicleViews(){const cartSeen=new Set();for(const c of carts.carts){cartSeen.add(c.id);let m=minecartViews.get(c.id);if(!m){m=new THREE.Mesh(new THREE.BoxGeometry(.9,.42,.9),new THREE.MeshLambertMaterial({color:0x62666a}));scene.add(m);minecartViews.set(c.id,m);}m.position.set(c.x,c.y+.22,c.z);}for(const[id,m]of minecartViews)if(!cartSeen.has(id)){scene.remove(m);m.geometry.dispose();m.material.dispose();minecartViews.delete(id);}const boatSeen=new Set();for(const b of boats.boats){boatSeen.add(b.id);let m=boatViews.get(b.id);if(!m){m=new THREE.Mesh(new THREE.BoxGeometry(1.25,.32,.72),new THREE.MeshLambertMaterial({color:0x9b6d3d}));scene.add(m);boatViews.set(b.id,m);}m.position.set(b.x,b.y+.18,b.z);m.rotation.y=b.yaw;}for(const[id,m]of boatViews)if(!boatSeen.has(id)){scene.remove(m);m.geometry.dispose();m.material.dispose();boatViews.delete(id);}}

function animate(now){const dt=Math.min(.05,Math.max(0,(now-lastFrame)/1000));lastFrame=now;if(ready){if(!paused){updatePlayer(dt);updateTarget();updateMining(dt);updateSimulation(dt);updateSky(dt);}else updateSky(0);updateRender(dt);updateStats(dt);}else{renderer.render(scene,camera);}}
renderer.setAnimationLoop(animate);

function updateStats(dt){fpsFrames++;fpsTime+=dt;if(fpsTime<.5)return;lastFps=Math.round(fpsFrames/fpsTime);fpsFrames=0;fpsTime=0;const cx=Math.floor(PLAYER.feet.x/16),cz=Math.floor(PLAYER.feet.z/16),biome=world.biomeAt(PLAYER.feet.x,PLAYER.feet.z);statsEl.textContent=`FPS ${lastFps} · XYZ ${PLAYER.feet.x.toFixed(1)} / ${PLAYER.feet.y.toFixed(1)} / ${PLAYER.feet.z.toFixed(1)} · chunk ${cx},${cz} · ${biome} · ${world.dimension} · ${entities.entities.length} entidades${multiplayer.connected?` · ${multiplayer.ping.toFixed(0)}ms`:''}`;renderSurvivalHud();localPresence.broadcast({x:PLAYER.feet.x,y:PLAYER.feet.y,z:PLAYER.feet.z,dimension:world.dimension});localPresence.cleanup();}

function changeDimension(id,{position=null}={}){if(!DIMENSIONS[id]||id===world.dimension)return false;saveCurrentWorld();world.setDimension(id);resetSystems(world);PLAYER.feet.set(position?.x??.5,position?.y??world.surfaceY(.5,.5)+.1,position?.z??.5);PLAYER.velocity.set(0,0,0);camera.position.set(PLAYER.feet.x,PLAYER.feet.y+PLAYER.eyeHeight,PLAYER.feet.z);showToast(`Entrou em ${DIMENSIONS[id].name}`);return true;}
function checkPortal(){const x=Math.floor(PLAYER.feet.x),y=Math.floor(PLAYER.feet.y+.7),z=Math.floor(PLAYER.feet.z);if(world.getBlock(x,y,z)!==BLOCK.PORTAL){portalTransit=false;return;}if(portalTransit||portal.cooldown>0)return;portalTransit=true;const target=world.getState(x,y,z)?.target||portal.targetDimension(world.dimension);changeDimension(target);portal.cooldown=3;}

function spawnBreakParticles(x,y,z,color,count=10){for(let i=0;i<count;i++){const mat=new THREE.MeshBasicMaterial({color}),m=new THREE.Mesh(particleGeo,mat);m.position.set(x+.5,y+.5,z+.5);const v=new THREE.Vector3((Math.random()-.5)*2.8,1+Math.random()*2.3,(Math.random()-.5)*2.8);particles.push({mesh:m,v,life:.4+Math.random()*.25});particleGroup.add(m);}}
function spawnExplosionParticles(x,y,z,power){for(let i=0;i<Math.min(90,power*18);i++){const color=Math.random()<.5?0xef9b36:0x4e4741;spawnBreakParticles(x-.5,y-.5,z-.5,color,1);const p=particles.at(-1);if(p)p.v.multiplyScalar(2+Math.random()*power);}}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.v.y-=7*dt;p.mesh.position.addScaledVector(p.v,dt);p.mesh.scale.setScalar(Math.max(.01,Math.min(1,p.life/.18)));if(p.life<=0){particleGroup.remove(p.mesh);p.mesh.material.dispose();particles.splice(i,1);}}}

function showToast(text){toast.textContent=String(text);toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),1700);}
function appendChat(html){if(!chatBox)return;const line=document.createElement('div');line.innerHTML=html;chatBox.appendChild(line);while(chatBox.children.length>40)chatBox.firstChild.remove();chatBox.scrollTop=chatBox.scrollHeight;chatBox.classList.add('active');clearTimeout(appendChat.timer);appendChat.timer=setTimeout(()=>chatBox.classList.remove('active'),5000);}
function runChat(text){const result=commandConsole.execute(text);if(result.type==='chat'&&multiplayer.connected)multiplayer.sendChat(result.message);else appendChat(`<span class="${result.ok?'ok':'error'}">${escapeHtml(result.message)}</span>`);if(result.ok)renderAllUI();}

controls.addEventListener('lock',()=>{unlockAudio();paused=false;inventoryOpen=false;inventoryPanel.classList.remove('visible');menu.classList.remove('visible');hud.classList.remove('hidden');hud.setAttribute('aria-hidden','false');keys.clear();});
controls.addEventListener('unlock',()=>{paused=true;cancelMining();keys.clear();hud.classList.add('hidden');hud.setAttribute('aria-hidden','true');if(inventoryOpen){menu.classList.remove('visible');inventoryPanel.classList.add('visible');}else if(!playerStats.dead){inventoryPanel.classList.remove('visible');menu.classList.add('visible');}saveCurrentWorld();});
playButton?.addEventListener('click',()=>{if(ready){unlockAudio();controls.lock();}});continueButton?.addEventListener('click',async()=>{if(worldSelect?.value)await loadWorld(worldSelect.value);controls.lock();});
newWorldButton?.addEventListener('click',async()=>{const seed=parseSeed(seedInput?.value),name=worldNameInput?.value||'Novo Mundo',gameMode=gameModeSelect?.value||'survival',difficulty=difficultySelect?.value||'normal';await createNewWorld({name,seed,gameMode,difficulty});});
saveButton?.addEventListener('click',async()=>{await saveCurrentWorld();showToast('Mundo salvo no IndexedDB.');});closeInventoryButton?.addEventListener('click',()=>{closeInventory();});respawnButton?.addEventListener('click',respawn);
exportButton?.addEventListener('click',async()=>{const text=await saveDB.exportWorld(currentWorldId),blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${currentWorldId}.voxelcraft.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
importButton?.addEventListener('click',()=>importFile?.click());importFile?.addEventListener('change',async()=>{const file=importFile.files?.[0];if(!file)return;try{const id=await saveDB.importWorld(await file.text());await refreshWorldList();await loadWorld(id);showToast('Mundo importado.');}catch(e){showToast(`Falha ao importar: ${e.message}`);}importFile.value='';});
settingsButton?.addEventListener('click',()=>settingsPanel?.classList.toggle('visible'));

addEventListener('keydown',(e)=>{if(chatInput===document.activeElement)return;if(e.code.startsWith('Digit')){const n=Number(e.code.slice(5))-1;if(n>=0&&n<9){inventory.setSelected(n);renderHotbar();}}if(e.code==='KeyE'&&controls.isLocked){e.preventDefault();openInventory('2x2');return;}if(e.code==='KeyF'&&controls.isLocked&&playerStats.gameMode==='creative'&&!e.repeat){flying=!flying;playToggleFly(flying);syncMode();return;}if(e.code==='KeyR'&&controls.isLocked&&!e.repeat){toggleVehicleMount();syncMode();return;}if(e.code==='F3'&&!e.repeat){e.preventDefault();debugVisible=!debugVisible;statsEl.classList.toggle('debug-hidden',!debugVisible);return;}if(e.code==='KeyT'&&controls.isLocked){e.preventDefault();controls.unlock();chatInput?.focus();return;}if(e.code==='Slash'&&controls.isLocked){e.preventDefault();controls.unlock();if(chatInput){chatInput.value='/';chatInput.focus();}return;}if(e.code==='Space'){e.preventDefault();if(!e.repeat)jumpQueued=true;}keys.add(e.code);});
addEventListener('keyup',(e)=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();cancelMining();});
canvas.addEventListener('mousedown',(e)=>{if(!controls.isLocked)return;e.preventDefault();if(e.button===0)startPrimary();if(e.button===2)secondaryAction();});canvas.addEventListener('mouseup',(e)=>{if(e.button===0)cancelMining();});canvas.addEventListener('contextmenu',(e)=>e.preventDefault());addEventListener('wheel',(e)=>{if(!controls.isLocked)return;inventory.setSelected((inventory.selected+(e.deltaY>0?1:-1)+9)%9);renderHotbar();},{passive:true});
chatInput?.addEventListener('keydown',(e)=>{if(e.key==='Enter'){const value=chatInput.value.trim();chatInput.value='';if(value)runChat(value);chatInput.blur();if(ready&&!playerStats.dead)setTimeout(()=>controls.lock(),50);}if(e.key==='Escape'){chatInput.value='';chatInput.blur();}});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,appSettings.resolutionScale));renderer.setSize(innerWidth,innerHeight,false);});addEventListener('beforeunload',()=>{saveCurrentWorld();localPresence.close();multiplayer.disconnect();});

setupSettingsUI();setupMultiplayerUI();
function setupSettingsUI(){if(!settingsPanel)return;settingsPanel.innerHTML=`<h3>Configurações</h3><label>FOV <input id="setFov" type="range" min="55" max="105" value="${appSettings.fov}"></label><label>Distância <input id="setRender" type="range" min="2" max="6" value="${appSettings.renderDistance}"></label><label>Resolução <input id="setScale" type="range" min="0.75" max="2" step="0.25" value="${appSettings.resolutionScale}"></label><label>Volume <input id="setVolume" type="range" min="0" max="0.6" step="0.02" value="${appSettings.volume}"></label>`;$('#setFov')?.addEventListener('input',(e)=>{appSettings.fov=Number(e.target.value);saveSettings();});$('#setRender')?.addEventListener('change',(e)=>{appSettings.renderDistance=Number(e.target.value);worldRenderer.renderRadius=appSettings.renderDistance;scene.fog.far=16*(appSettings.renderDistance+2.5);saveSettings();});$('#setScale')?.addEventListener('change',(e)=>{appSettings.resolutionScale=Number(e.target.value);renderer.setPixelRatio(Math.min(devicePixelRatio,appSettings.resolutionScale));saveSettings();});$('#setVolume')?.addEventListener('input',(e)=>{appSettings.volume=Number(e.target.value);setMasterVolume(appSettings.volume);saveSettings();});}
function setupMultiplayerUI(){if(!multiplayerPanel)return;multiplayerPanel.innerHTML=`<h3>Multiplayer</h3><input id="mpUrl" placeholder="ws://servidor:8787"><input id="mpRoom" value="default" placeholder="Sala"><input id="mpName" value="Player" placeholder="Nome"><button id="mpConnect">Conectar</button><span id="mpStatus">offline</span>`;$('#mpConnect')?.addEventListener('click',async()=>{const url=$('#mpUrl')?.value;if(!url)return showToast('Informe o WebSocket do servidor.');try{const welcome=await multiplayer.connect(url,$('#mpRoom')?.value||'default',$('#mpName')?.value||'Player');$('#mpStatus').textContent=`conectado · ${welcome.room}`;if(welcome.seed&&welcome.seed!==world.seed)showToast(`Servidor usa seed ${welcome.seed}`);setInterval(()=>multiplayer.pingServer(),5000);}catch(e){$('#mpStatus').textContent='falha';showToast(e.message);}});}

setInterval(()=>{if(!multiplayer.connected||!controls.isLocked)return;camera.getWorldDirection(forward);const localForward=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),localRight=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),yaw=camera.rotation.y,mx=Math.sin(yaw)*localForward+Math.cos(yaw)*localRight,mz=-Math.cos(yaw)*localForward+Math.sin(yaw)*localRight;multiplayer.sendInput({mx,mz,my:flying?((keys.has('Space')?1:0)-(keys.has('ControlLeft')?1:0)):0,yaw:camera.rotation.y,pitch:camera.rotation.x,sprint:keys.has('ShiftLeft'),jump:jumpQueued});},50);

function parseSeed(value){const text=String(value||'').trim();if(!text)return randomSeed();const n=Number(text);if(Number.isFinite(n))return Math.abs(Math.floor(n))||1;let h=2166136261;for(const ch of text){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0)||1;}
function randomSeed(){return Math.floor(Math.random()*2_000_000_000)+1;}
function ensureHudElement(id){let el=$(`#${id}`);if(!el){el=document.createElement('div');el.id=id;hud.appendChild(el);}return el;}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function loadSettings(){try{return{fov:75,renderDistance:3,resolutionScale:1.5,volume:.22,...JSON.parse(localStorage.getItem('voxelcraft-v1-settings')||'{}')}}catch{return{fov:75,renderDistance:3,resolutionScale:1.5,volume:.22};}}
function saveSettings(){localStorage.setItem('voxelcraft-v1-settings',JSON.stringify(appSettings));}
function applySettings(){camera.fov=appSettings.fov;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,appSettings.resolutionScale));setMasterVolume(appSettings.volume);}
function createStars(){const count=900,p=new Float32Array(count*3);for(let i=0;i<count;i++){const r=130,a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1);p[i*3]=Math.sin(b)*Math.cos(a)*r;p[i*3+1]=Math.abs(Math.cos(b))*r;p[i*3+2]=Math.sin(b)*Math.sin(a)*r;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));return new THREE.Points(g,new THREE.PointsMaterial({color:0xffffff,size:.65,sizeAttenuation:true}));}
function publicApi(){return{get world(){return world},get inventory(){return inventory},get stats(){return playerStats},get entities(){return entities},get rules(){return rules},get renderer(){return renderer},get vehicles(){return{carts,boats,mounted:mountedVehicle}},save:saveCurrentWorld,load:loadWorld,newWorld:createNewWorld,command:(s)=>commandConsole.execute(s),changeDimension,explode:(p=4)=>explode(world,PLAYER.feet.x,PLAYER.feet.y,PLAYER.feet.z,p),state:()=>({ready,paused,worldId:currentWorldId,dimension:world.dimension,player:[PLAYER.feet.x,PLAYER.feet.y,PLAYER.feet.z],fps:lastFps,mountedVehicle})};}